---
title: Get sequence of variants 01
subtitle: Arrange variant table into bed format
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [1]:
import numpy  as np
import pandas as pd
import os

In [2]:
%run ../run_config_project.py
show_env()

BASE DIRECTORY (FD_BASE): /hpc/group/igvf/kk319
REPO DIRECTORY (FD_REPO): /hpc/group/igvf/kk319/repo
WORK DIRECTORY (FD_WORK): /hpc/group/igvf/kk319/work
DATA DIRECTORY (FD_DATA): /hpc/group/igvf/kk319/data


You are working with      IGVF BlueSTARR
PATH OF PROJECT (FD_PRJ): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR
PROJECT RESULTS (FD_RES): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/results
PROJECT SCRIPTS (FD_EXE): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/scripts
PROJECT DATA    (FD_DAT): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/data
PROJECT NOTE    (FD_NBK): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/notebooks
PROJECT DOCS    (FD_DOC): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/docs
PROJECT LOG     (FD_LOG): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/log
PROJECT REF     (FD_REF): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/references

## Import data

**Check file existent**

In [3]:
%%bash -s "{FD_DAT}"
echo $1

/hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/data

In [4]:
!ls $FD_DAT/variant_bluestarr_richard/closed

delta_effects.tsv.gz  old_files  regions.fasta.gz

**Import table**

In [5]:
### set file directory
txt_fdiry = os.path.join(FD_DAT, "variant_bluestarr_richard", "closed")
txt_fname = "delta_effects.tsv.gz"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### read table
dat = pd.read_csv(txt_fpath, sep = "\t")

### assign and show
dat_variant_import = dat
print(dat.shape)
dat.head()

(1885038, 12)

,region,pos0,delta,rank4,rank3,rank2,rank1,var_type4,var_type3,ref,obs_used,unobs_used
0,chr2:234143174-234143434,234143291,1.708901,C,T,A,G,ref,snv,C,C,G
1,chr6:111030999-111031188,111031101,1.625281,G,A,T,C,snv,ref,A,G,C
2,chr5:73091238-73091414,73091405,1.597880,C,T,G,A,snv,ref,T,C,A
3,chr2:37426938-37427245,37427187,1.526402,G,A,C,T,ref,snv,G,G,T
4,chr6:27903836-27904383,27904376,1.502800,C,G,T,A,snv,ref,G,C,A

## Arrange table

In [6]:
### init
dat = dat_variant_import.copy()

### split region into chrom/start/end
dat_chrom_info    = dat["region"].str.split("[:-]", expand=True)
dat["Chrom"]      = dat_chrom_info[0]
dat["ChromStart"] = dat_chrom_info[1].astype(int)
dat["ChromEnd"]   = dat_chrom_info[2].astype(int)

### rename original columns
dat = dat.rename(columns={
    "region": "Region",
    "pos0":   "Pos0",
    "delta":  "Delta"
})
dat = dat.rename(columns={
    "ref":        "Ref",
    "obs_used":   "Obs",
    "unobs_used": "Unobs"
})
dat = dat.rename(columns={
    "rank4": "Rank4",
    "rank3": "Rank3",
    "rank2": "Rank2",
    "rank1": "Rank1"
})

### add Variant_ID
dat["Variant_Ref"] = (
    dat["Chrom"].astype(str) + ":" +
    dat["Pos0"].astype(str)  + ":" +
    dat["Ref"].astype(str) 
)

dat["Variant_UnObs_vs_Obs"] = (
    dat["Chrom"].astype(str) + ":" +
    dat["Pos0"].astype(str)  + ":" +
    dat["Ref"].astype(str)   + ":" + 
    dat["Obs"]               + ":" + 
    dat["Unobs"]
)


### Reorder columns
dat = dat[[
    "Chrom", "ChromStart", "ChromEnd", "Region", 
    "Variant_Ref", 
    "Variant_UnObs_vs_Obs",
    "Pos0",
    "Rank4", "Rank3", "Rank2", "Rank1",
    "Ref", "Obs", "Unobs",
    "Delta"
]]

### sort by Delta (highest -> smallest)
dat = dat.sort_values(by="Delta", ascending=False)

### assign and show
dat_variant_arrange = dat
print(dat.shape)
dat.head()

(1885038, 15)

,Chrom,ChromStart,ChromEnd,Region,Variant_Ref,Variant_UnObs_vs_Obs,Pos0,Rank4,Rank3,Rank2,Rank1,Ref,Obs,Unobs,Delta
0,chr2,234143174,234143434,chr2:234143174-234143434,chr2:234143291:C,chr2:234143291:C:C:G,234143291,C,T,A,G,C,C,G,1.708901
1,chr6,111030999,111031188,chr6:111030999-111031188,chr6:111031101:A,chr6:111031101:A:G:C,111031101,G,A,T,C,A,G,C,1.625281
2,chr5,73091238,73091414,chr5:73091238-73091414,chr5:73091405:T,chr5:73091405:T:C:A,73091405,C,T,G,A,T,C,A,1.597880
3,chr2,37426938,37427245,chr2:37426938-37427245,chr2:37427187:G,chr2:37427187:G:G:T,37427187,G,A,C,T,G,G,T,1.526402
4,chr6,27903836,27904383,chr6:27903836-27904383,chr6:27904376:G,chr6:27904376:G:C:A,27904376,C,G,T,A,G,C,A,1.502800

## Export table

In [7]:
### set file directory
txt_fdiry = os.path.join(FD_RES, "analysis_variant_motif_richard")
txt_fname = "variant_closed_gof_bluestarr.tsv"
txt_fpath = os.path.join(txt_fdiry, txt_fname)

### write table
dat_variant_arrange.to_csv(txt_fpath, sep="\t", index=False)