---
title: Variant results from Richard 02
subtitle: Explore tables 
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [2]:
suppressMessages(suppressWarnings(source("../run_config_project.R")))
suppressMessages(suppressWarnings(library("xgboost")))
suppressMessages(suppressWarnings(library("Matrix")))
show_env()

BASE DIRECTORY (FD_BASE): /hpc/group/igvf/kk319
REPO DIRECTORY (FD_REPO): /hpc/group/igvf/kk319/repo
WORK DIRECTORY (FD_WORK): /hpc/group/igvf/kk319/work
DATA DIRECTORY (FD_DATA): /hpc/group/igvf/kk319/data

You are working with      IGVF BlueSTARR
PATH OF PROJECT (FD_PRJ): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR
PROJECT RESULTS (FD_RES): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/results
PROJECT SCRIPTS (FD_EXE): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/scripts
PROJECT DATA    (FD_DAT): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/data
PROJECT NOTE    (FD_NBK): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/notebooks
PROJECT DOCS    (FD_DOC): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/docs
PROJECT LOG     (FD_LOG): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/log
PROJECT REF     (FD_REF): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/references

## Import data

**Check file existence**

In [3]:
### set file directory
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard")

vec = dir(txt_fdiry)
for (txt in vec){cat(txt, "\n")}

background_zero_order.npy
background_zero_order.tsv
batches_dev
batches_pilot_low_dinuc
batches_pilot_low_ori
batches_pilot_top_dinuc
batches_pilot_top_ori
batches_top_dinuc
batches_top_ori
motif_jaspar2024_core_vertebrates_nonredundant.lods.pkl
motif_jaspar2024_core_vertebrates_nonredundant.pmap.pkl
motif_jaspar2024_core_vertebrates_nonredundant.tbind.pkl
motif_nonredundant_jvierstra_v2.1beta.lods.pkl
motif_nonredundant_jvierstra_v2.1beta.pmap.pkl
motif_nonredundant_jvierstra_v2.1beta.tbind.pkl
motifcount_pilot_jvierstra_v2.1beta
motifdelta_pilot_low_dinuc_jvierstra_v2.1beta
motifdelta_pilot_low_ori_jvierstra_v2.1beta
motifdelta_pilot_top_dinuc_jvierstra_v2.1beta
motifdelta_pilot_top_ori_jvierstra_v2.1beta
motifdelta_top_dinuc_jaspar2024
motifdelta_top_dinuc_jvierstra_v2.1beta
motifdelta_top_ori_jaspar2024
motifdelta_top_ori_jvierstra_v2.1beta
motifmodel_pilot_jvierstra_v2.1beta
motifscan_pilot_low_dinuc_jvierstra_v2.1beta
motifscan_pilot_low_ori_jvierstra_v2.1beta
motifscan_pilot_top_dinuc_jvierstra_v2.1beta
motifscan_pilot_top_ori_jvierstra_v2.1beta
motifscan_top_dinuc_jaspar2024
motifscan_top_dinuc_jvierstra_v2.1beta
motifscan_top_ori_jaspar2024
motifscan_top_ori_jvierstra_v2.1beta
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.ref.fa
variant_closed_gof_bluestarr.tsv

In [5]:
### set file directory

txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard")
txt_fname  = "variant_closed_gof_bluestarr.tsv"
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### assign and show
dat_bluestarr_variant_import = dat
print(dim(dat))
fun_display_table(head(dat, 3))

[1] 1885038      15

Chrom,ChromStart,ChromEnd,Region,Variant_Ref,Variant_UnObs_vs_Obs,Pos0,Rank4,Rank3,Rank2,Rank1,Ref,Obs,Unobs,Delta
chr2,234143174,234143434,chr2:234143174-234143434,chr2:234143291:C,chr2:234143291:C:C:G,234143291,C,T,A,G,C,C,G,1.708901
chr6,111030999,111031188,chr6:111030999-111031188,chr6:111031101:A,chr6:111031101:A:G:C,111031101,G,A,T,C,A,G,C,1.625281
chr5,73091238,73091414,chr5:73091238-73091414,chr5:73091405:T,chr5:73091405:T:C:A,73091405,C,T,G,A,T,C,A,1.597880

In [22]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifdelta_pilot_top_ori_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot_top_merge.delta.event.tsv", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### assign and show
dat_motifdelta_top_ori_event_import = dat
print(dim(dat))
fun_display_table(head(dat, 3))

[1] 2971052       9

Chunk_Prefix,Variant_ID,Motif_Name,Position,Strand,Delta,Obs,Ubs,Event_Type
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot_top_chunk001,chr2:234143291:C:C:G,AC0014:BATF/FOSL:bZIP AC0014:BATF/FOSL:bZIP,34,Reverse,3.974146,3.4969823,7.471128,Gain
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot_top_chunk001,chr2:234143291:C:C:G,AC0093:ZNF:C2H2_ZF AC0093:ZNF:C2H2_ZF,15,Forward,1.963745,-0.6802492,1.283496,Gain
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot_top_chunk001,chr2:234143291:C:C:G,AC0096:ZNF:C2H2_ZF AC0096:ZNF:C2H2_ZF,33,Forward,5.149051,-0.0121756,5.136876,Gain

In [23]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifdelta_pilot_low_ori_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot_low_merge.delta.event.tsv", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### assign and show
dat_motifdelta_low_ori_event_import = dat
print(dim(dat))
fun_display_table(head(dat, 3))

[1] 1486316       9

Chunk_Prefix,Variant_ID,Motif_Name,Position,Strand,Delta,Obs,Ubs,Event_Type
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot_low_chunk001,chr2:186926228:A:A:C,AC0071:MYB:Myb/SANT AC0071:MYB:Myb/SANT,35,Forward,20.644424,-16.3024006,4.342024,Gain
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot_low_chunk001,chr2:186926228:A:A:C,AC0191:IRF:IRF AC0191:IRF:IRF,25,Reverse,10.197981,-3.0341692,7.163812,Gain
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot_low_chunk001,chr2:186926228:A:A:C,AC0343:ZNF:C2H2_ZF AC0343:ZNF:C2H2_ZF,15,Forward,2.442278,0.0615872,2.503866,Gain

In [18]:
### set file directory
txt_folder = "motifcount_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)

vec = dir(txt_fdiry)
for (txt in vec){cat(txt, "\n")}

variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.motif.count.tsv
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.motif.enrich.tsv

In [2]:
### set file directory
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)

vec = dir(txt_fdiry)
for (txt in vec){cat(txt, "\n")}

variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.cv.evaluation_log.tsv
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.cv.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.params.used.json
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.resid.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.shap.meta.txt
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.shap.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.shap.summary.tsv
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.summary.txt
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.train_metrics.txt
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.X.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.xgb_model.bin
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.yhat.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.dinuc.yhat.tsv
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.cv.evaluation_log.tsv
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.cv.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.params.used.json
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.resid.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.shap.meta.txt
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.shap.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.shap.summary.tsv
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.summary.txt
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.train_metrics.txt
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.X.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.xgb_model.bin
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.yhat.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.yhat.tsv
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.xgb_cv.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.xgb_model.bin
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.y.rds
xbg_cv_train_params.json

### Import data

In [19]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifcount_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.motif.enrich.tsv", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### assign and show
dat_motif_enrich_import = dat
print(dim(dat))
fun_display_table(head(dat))

[1] 1258   10

Direction,Motif_Name,Beta_Est,OddsRatio,Beta_SE,Beta_Z,Beta_Pval,Beta_Padj,Log10Beta,NLog10Padj
Count_Gain,AC0001:GATA/PROP:GATA,0.1921645,1.2118699,0.0928337,2.069986,0.0384537,0.0666318,0.0834560,1.1763184
Count_Gain,AC0002:PROP/ALX:Homeodomain,0.8336586,2.3017246,0.0703133,11.856343,0.0000000,0.0000000,0.3620533,30.4065576
Count_Gain,AC0003:HNF1A/HNF1B:Homeodomain,0.0813782,1.0847811,0.0761162,1.069131,0.2850106,0.3719329,0.0353421,0.4295354
Count_Gain,AC0004:ZSCAN:C2H2_ZF,-0.2531942,0.7763171,0.1324355,-1.911830,0.0558980,0.0922831,-0.1099608,1.0348779
Count_Gain,"AC0005:POU3F/POU1F:Homeodomain,POU",-0.1404850,0.8689367,0.0655264,-2.143943,0.0320374,0.0567649,-0.0610118,1.2459199
Count_Gain,AC0006:MEOX:Homeodomain,0.2092501,1.2327532,0.0696715,3.003379,0.0026700,0.0058321,0.0908761,2.2341764

In [3]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.y.rds", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
obj = read_rds(txt_fpath)

### assign and show
vec_y_ori_import = obj
print(class(obj))
print(length(obj))
print(head(obj))

[1] "numeric"
[1] 199971
chr1:100186033:T:T:A chr1:100306767:A:A:C chr1:100307737:G:G:C
           0.1147592            0.1031407            0.1006881
chr1:100324154:G:G:C chr1:100520609:T:C:G chr1:100521850:A:A:T
           0.0812454            0.1144301            0.1018046

In [4]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.ori.yhat.rds", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
obj = read_rds(txt_fpath)

### assign and show
vec_yhat_ori_import = obj
print(class(obj))
print(length(obj))
print(head(obj))

[1] "numeric"
[1] 199971
[1] 0.10188500 0.06695375 0.12258269 0.06394247 0.05081124 0.05099595

In [5]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.ori.shap.rds", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
obj = read_rds(txt_fpath)

### assign and show
mat_shap_ori_import = obj
print(class(obj))
print(dim(obj))
fun_display_table(head(obj))
rm(obj)

[1] "matrix" "array"
[1] 199971    630

AC0001:GATA/PROP:GATA,AC0002:PROP/ALX:Homeodomain,AC0003:HNF1A/HNF1B:Homeodomain,AC0004:ZSCAN:C2H2_ZF,"AC0005:POU3F/POU1F:Homeodomain,POU",AC0006:MEOX:Homeodomain,AC0007:BARX/NKX:Homeodomain,AC0008:VENTX:Homeodomain,AC0009:PAX/VSX:Homeodomain,AC0010:DLX/LHX:Homeodomain,AC0011:POU6F/NKX:Homeodomain,AC0012:SATB:['Homeo_domain_factors'],AC0013:SIX:Homeodomain,AC0014:BATF/FOSL:bZIP,AC0015:RUNX:Runt,AC0016:KLF:C2H2_ZF,AC0017:RUNX:Runt,AC0018:ZBTB:C2H2_ZF,AC0019:AIRE:SAND,AC0020:CENPB:CENPB,AC0021:ZNF:C2H2_ZF,AC0022:ZNF:C2H2_ZF,AC0023:ZNF:C2H2_ZF,AC0024:ZNF:C2H2_ZF,AC0025:ZNF:C2H2_ZF,AC0026:ZKSCAN:C2H2_ZF,AC0027:ZNF:C2H2_ZF,AC0028:KLF:C2H2_ZF,AC0029:ZNF:C2H2_ZF,AC0030:ZNF:C2H2_ZF,"AC0031:POU3F/POU2F:Homeodomain,POU",AC0032:SIX/ZNF:Homeodomain,AC0033:PRDM:C2H2_ZF,AC0034:NR2F/NR1H:Nuclear_receptor,AC0035:ZNF:C2H2_ZF,AC0036:BCL11A/BCL11B:C2H2_ZF,AC0037:ZNF:C2H2_ZF,AC0038:THAP:['C2CH_THAP-type_zinc_finger_factors'],AC0039:TFAP2A/TFAP2C:AP-2,AC0040:ZNF:C2H2_ZF,AC0041:ZNF:C2H2_ZF,AC0042:ZSCAN:C2H2_ZF,AC0043:TFAP2A/TFAP2C:AP-2,AC0044:ZNF:C2H2_ZF,AC0045:ZNF:C2H2_ZF,AC0046:EBF:['Rel_homology_region_(RHR)_factors'],AC0047:ZNF:C2H2_ZF,AC0048:ZNF:C2H2_ZF,AC0049:PLAGL:C2H2_ZF,AC0050:ZNF:C2H2_ZF,AC0051:PLAG:C2H2_ZF,AC0052:ZNF:C2H2_ZF,AC0053:ZNF:C2H2_ZF,AC0054:ZFX/ZNF:C2H2_ZF,AC0055:ZNF:C2H2_ZF,AC0056:ZNF/SP:C2H2_ZF,AC0057:ZBTB/ZNF:C2H2_ZF,AC0058:ZNF:C2H2_ZF,AC0059:YY/ZFP:C2H2_ZF,AC0060:YY/MZF:C2H2_ZF,AC0061:YY:C2H2_ZF,AC0062:ZNF:C2H2_ZF,AC0063:ZNF:C2H2_ZF,AC0064:RFX/MXI:RFX,AC0065:RFX:RFX,AC0066:RFX:RFX,AC0067:RFX:RFX,AC0068:HIC:C2H2_ZF,AC0069:ZNF:C2H2_ZF,AC0070:MYB/MYBL:Myb/SANT,AC0071:MYB:Myb/SANT,AC0072:MYBL:Myb/SANT,AC0073:MYBL:Myb/SANT,AC0074:MYBL:Myb/SANT,AC0075:OVOL:C2H2_ZF,AC0076:OVOL:C2H2_ZF,AC0077:ZIC/GLIS:C2H2_ZF,AC0078:CTCF/CTCFL:C2H2_ZF,AC0079:ZNF:C2H2_ZF,AC0080:ZNF:C2H2_ZF,AC0081:NFIA/NFIC:SMAD,AC0082:NFIX/NFIC:SMAD,AC0083:ZBTB:C2H2_ZF,AC0084:HIC:C2H2_ZF,AC0085:ZNF:C2H2_ZF,AC0086:ZNF:C2H2_ZF,AC0087:E2F:E2F,AC0088:ZNF:C2H2_ZF,AC0089:ZNF:C2H2_ZF,AC0091:ZNF:C2H2_ZF,AC0092:ZNF:C2H2_ZF,AC0093:ZNF:C2H2_ZF,AC0094:ZNF:C2H2_ZF,AC0095:E2F:E2F,AC0096:ZNF:C2H2_ZF,AC0098:ZNF:C2H2_ZF,AC0099:ZNF:C2H2_ZF,AC0100:ZNF:C2H2_ZF,AC0101:ZBTB:C2H2_ZF,AC0102:ZNF:C2H2_ZF,AC0103:ZBTB:['C2H2_zinc_finger_factors'],AC0104:ZNF:C2H2_ZF,AC0105:EGR/ZNF:C2H2_ZF,AC0106:EGR/WT:C2H2_ZF,AC0107:KLF:C2H2_ZF,AC0108:KLF/SP:C2H2_ZF,AC0109:SP/KLF:C2H2_ZF,AC0110:ZNF/MAZ:C2H2_ZF,AC0111:CTCF/KLF:C2H2_ZF,"AC0112:PAX:Homeodomain,Paired_box",AC0113:ZNF:C2H2_ZF,AC0114:ZNF/VEZF:C2H2_ZF,AC0115:ZNF:C2H2_ZF,AC0116:GLIS:C2H2_ZF,AC0117:GLI/ZIC:C2H2_ZF,AC0118:ZBTB7A:C2H2_ZF,AC0119:ZBTB7A/ZBTB7B:C2H2_ZF,AC0120:RREB:C2H2_ZF,AC0121:ZNF:C2H2_ZF,AC0122:XPA:Unknown,AC0123:FOXO:Forkhead,AC0124:ZNF:C2H2_ZF,AC0125:ZNF:C2H2_ZF,AC0126:ZNF:C2H2_ZF,AC0127:ZFP:C2H2_ZF,AC0128:TFCP:Grainyhead,AC0129:THAP:THAP_finger,AC0130:GCM:GCM,AC0131:ZNF:C2H2_ZF,AC0132:ZSCAN/KLF:C2H2_ZF,AC0133:ZNF:C2H2_ZF,AC0134:HSF:HSF,AC0135:ZBTB:C2H2_ZF,AC0136:INSM:C2H2_ZF,AC0137:ZNF:C2H2_ZF,AC0138:GTF3A:C2H2_ZF,AC0139:ZNF:C2H2_ZF,AC0140:ZNF75A/ZNF75D:C2H2_ZF,AC0141:IKZF:C2H2_ZF,AC0142:IKZF:C2H2_ZF,AC0143:RBPJ:CSL,AC0144:IKZF/NFKB:C2H2_ZF,AC0145:ZNF:C2H2_ZF,AC0146:ZNF/ZNF324B:['C2H2_zinc_finger_factors'],AC0147:ZNF:C2H2_ZF,AC0148:ZNF:C2H2_ZF,AC0149:ZNF:C2H2_ZF,AC0150:ZNF:C2H2_ZF,AC0151:ZNF:C2H2_ZF,AC0152:ZNF:C2H2_ZF,AC0153:ZNF:C2H2_ZF,AC0154:ZNF:C2H2_ZF,AC0155:ETS/SIX:Ets,AC0156:ZNF:C2H2_ZF,AC0157:ZFP:['C2H2_zinc_finger_factors'],AC0158:E2F/TFDP:E2F,AC0159:E2F:E2F,AC0160:BCL11B:C2H2_ZF,AC0161:E2F/ZBTB:E2F,AC0162:ZNF:C2H2_ZF,AC0163:ZNF:C2H2_ZF,AC0164:ZNF:C2H2_ZF,AC0165:ZNF:C2H2_ZF,AC0166:ZFP:C2H2_ZF,AC0167:ZNF:C2H2_ZF,AC0168:ZNF:C2H2_ZF,AC0169:ZNF/PRDM:C2H2_ZF,AC0170:FLI/ZNF:Ets,AC0171:RBAK/ZNF:C2H2_ZF,AC0172:ZNF:C2H2_ZF,AC0173:ZNF:C2H2_ZF,AC0174:ZSCAN:C2H2_ZF,AC0175:MZF:C2H2_ZF,AC0176:MZF:C2H2_ZF,AC0177:ZNF/MZF:C2H2_ZF,AC0178:ZNF:C2H2_ZF,AC0179:ZNF:C2H2_ZF,AC0180:ZSCAN/ZNF:C2H2_ZF,AC0181:ZNF:C2H2_ZF,AC0182:ZNF:C2H2_ZF,AC0183:ZNF:C2H2_ZF,AC0184:ZNF:C2H2_ZF,AC0185:ZNF:C2H2_ZF,AC0186:ZNF:C2H2_ZF,AC0187:IRF:IRF,AC0188:IRF/STAT:IRF,AC0189:IRF:IRF,AC0190:IRF/ZBED:IRF,AC0191:IRF:IRF,AC0192:PRDM:C2H2_ZF,AC0193:ZNF:C2H2_ZF,AC0194:ZNF:C2H2_ZF,AC0195:ZNF:C2H2_ZF,AC0196:NFKB/RELA:Rel,AC0197:ZBTB:C2H2_ZF,AC0198:ZBTB:C2H2_ZF,AC0199:HSF:HSF,AC0200:ZNF:C2H2_ZF,AC0201:TEAD:TEA,AC0202:ZNF:C2H2_ZF,AC0203:ZNF:C2H2_ZF,AC0204:ZNF33B:C2H2_ZF,AC0205:NFATC/STAT:Rel,AC0206:NFATC:Rel,AC0207:NFAT/NFATC:Rel,AC0208:NFATC/ZNF:Rel,AC0209:ZNF:C2H2_ZF,AC0210:BCL/BCL6B:C2H2_ZF,AC0211:ZNF:C2H2_ZF,AC0212:STAT/STAT5A:STAT,AC0213:STAT/STAT5A:STAT,AC0214:OSR:C2H2_ZF,AC0215:ZNF:C2H2_ZF,AC0216:ZNF:C2H2_ZF,AC0217:ZNF:C2H2_ZF,AC0218:ZSCAN:C2H2_ZF,AC0219:HMBOX:Homeodomain,AC0220:ZNF:C2H2_ZF,AC0221:EN:Homeodomain,AC0222:MYNN:C2H2_ZF,AC0223:ZNF:C2H2_ZF,AC0224:ZNF:C2H2_ZF,AC0225:ZNF33A:C2H2_ZF,AC0226:ZKSCAN:['C2H2_zinc_finger_factors'],AC0227:SPI/BCL11A:Ets,AC0228:CTCF:C2H2_ZF,AC0229:ZFP:C2H2_ZF,AC0230:MECP:MBD,"AC0231:PAX:Homeodomain,Paired_box",AC0232:SMAD:['SMAD/NF-1_DNA-binding_domain_factors'],AC0233:HINFP:['C2H2_zinc_finger_factors'],AC0234:HINFP:C2H2_ZF,AC0235:HINFP:C2H2_ZF,AC0236:BATF/IRF:bZIP,AC0237:ZNF:C2H2_ZF,AC0238:ZNF:C2H2_ZF,AC0239:BACH/NFE:bZIP,AC0240:ZNF:C2H2_ZF,AC0241:NFE2L/JUN:bZIP,AC0242:FOSL/JUND:bZIP,AC0243:ZSCAN5C:C2H2_ZF,AC0244:MAFG/MAFF:bZIP,AC0245:ZBTB:C2H2_ZF,AC0246:MAFF/MAF:bZIP,AC0247:ZNF:C2H2_ZF,AC0248:ZNF:C2H2_ZF,AC0249:ZNF:C2H2_ZF,AC0250:MECOM/ZSCAN:C2H2_ZF,AC0251:MECOM:C2H2_ZF,AC0252:GATA/GATA1::TAL:GATA,AC0253:GATA:GATA,AC0254:GATA/TRPS:GATA,AC0255:GATA:GATA,AC0256:GFI:C2H2_ZF,AC0257:FOXG/FOXK:Forkhead,AC0258:SOX:Sox,AC0259:SOX:Sox,AC0260:SOX:Sox,AC0261:SOX/SRY:Sox,AC0262:SOX/SRY:Sox,AC0263:SOX/SRY:Sox,AC0264:FOXD:Forkhead,AC0265:FOXJ:Forkhead,AC0266:ZNF:C2H2_ZF,AC0267:SOX/SRY:Sox,AC0268:ZNF:C2H2_ZF,"AC0269:CUX:CUT,Homeodomain",AC0270:BBX:Sox,AC0271:SOX/SRY:Sox,AC0272:HSFY:HSF,AC0273:MTF:C2H2_ZF,"AC0274:PAX:Homeodomain,Paired_box",AC0275:ZNF33A:C2H2_ZF,AC0276:ZNF:C2H2_ZF,AC0277:ZNF:C2H2_ZF,AC0278:ZFP:C2H2_ZF,AC0279:ZNF:C2H2_ZF,AC0280:ZNF:['C2H2_zinc_finger_factors'],AC0281:ZKSCAN:C2H2_ZF,AC0282:SMAD:SMAD,"AC0283:ZSCAN:C2H2_ZF,MADF",AC0284:ZNF:C2H2_ZF,AC0285:ZFP:C2H2_ZF,AC0286:ZNF33A:C2H2_ZF,AC0287:ZNF:['C2H2_zinc_finger_factors'],AC0288:ZNF:C2H2_ZF,AC0289:ZNF:['C2H2_zinc_finger_factors'],AC0290:FOXP:Forkhead,AC0291:ZFP/ZNF:C2H2_ZF,AC0292:ZBTB:C2H2_ZF,AC0293:ZNF:C2H2_ZF,AC0294:ZNF:C2H2_ZF,AC0295:ZNF:C2H2_ZF,AC0296:ZNF:C2H2_ZF,AC0297:ZNF:C2H2_ZF,AC0298:PRDM:C2H2_ZF,AC0299:HMX:Homeodomain,AC0300:ZNF:C2H2_ZF,AC0301:ZNF:C2H2_ZF,AC0302:ZNF:C2H2_ZF,AC0303:ZNF:C2H2_ZF,AC0304:ZFP:C2H2_ZF,AC0305:ZNF:C2H2_ZF,AC0306:TOPORS:Unknown,AC0307:ZNF:C2H2_ZF,AC0308:ZNF:C2H2_ZF,AC0309:ZNF:C2H2_ZF,AC0310:ZNF:C2H2_ZF,AC0311:CTCF:C2H2_ZF,AC0312:ZNF:C2H2_ZF,AC0313:ZNF:C2H2_ZF,AC0314:ZNF:C2H2_ZF,AC0315:ZNF:C2H2_ZF,AC0316:ZNF:C2H2_ZF,AC0317:ZNF:C2H2_ZF,AC0318:ZBTB:C2H2_ZF,AC0319:ZBTB:C2H2_ZF,AC0320:ZNF:C2H2_ZF,AC0321:LEF/TCF:Sox,AC0322:ZNF:C2H2_ZF,AC0323:ZNF:C2H2_ZF,AC0324:MBD:MBD,AC0325:ZNF705G/ZNF:C2H2_ZF,AC0326:ZNF:C2H2_ZF,AC0327:ZBTB:C2H2_ZF,AC0328:ATF/ATF6B:bZIP,AC0329:ZNF/ZNF354C:C2H2_ZF,AC0330:LIN28B:CSD,AC0331:YBX:CSD,AC0332:ZNF:C2H2_ZF,AC0333:ZNF:C2H2_ZF,AC0334:ZNF:C2H2_ZF,AC0335:NRF:Unknown,AC0336:ZNF:C2H2_ZF,AC0337:ZNF:C2H2_ZF,AC0338:ARID5B:ARID/BRIGHT,AC0339:ZNF:['C2H2_zinc_finger_factors'],AC0340:ZNF:C2H2_ZF,AC0341:ZNF:C2H2_ZF,AC0342:ZNF:C2H2_ZF,AC0343:ZNF:C2H2_ZF,AC0344:ZNF:C2H2_ZF,AC0345:ZNF:C2H2_ZF,AC0346:ZNF:C2H2_ZF,AC0347:ZNF:C2H2_ZF,AC0348:TP:p53,AC0349:IRX:Homeodomain,AC0350:TFCP/TFCP2L:Grainyhead,AC0351:GRHL/TFCP:Grainyhead,AC0352:ZNF:C2H2_ZF,AC0353:PRDM:C2H2_ZF,AC0354:PRDM/ZEB:['C2H2_zinc_finger_factors'],AC0355:DMRTC:DM,AC0356:DMRT/DMRTA:DM,AC0357:FOXP:Forkhead,AC0359:SRF/MEF2B:MADS_box,AC0360:MYRF:Ndt80/PhoG,AC0361:MEF2A/MEF2C:MADS_box,AC0362:DPF/ZBTB:C2H2_ZF,AC0363:ZBTB:C2H2_ZF,AC0364:ZSCAN:C2H2_ZF,AC0365:ZIM/ZNF:C2H2_ZF,AC0366:ZNF:C2H2_ZF,AC0367:ZNF:C2H2_ZF,AC0368:ZNF:C2H2_ZF,AC0369:ZNF:C2H2_ZF,AC0370:ZNF/ZNF280A:C2H2_ZF,AC0371:REST:C2H2_ZF,AC0372:ZNF:C2H2_ZF,AC0373:ZBTB:C2H2_ZF,AC0374:CDC5L:Myb/SANT,AC0375:ZBTB/BANP:C2H2_ZF,AC0376:ZBED:BED_ZF,AC0377:ZNF385D:C2H2_ZF,AC0378:FOXH:Forkhead,AC0379:FOXK/FOXC:Forkhead,AC0381:SRY:Sox,AC0382:FOXA/FOXB:Forkhead,AC0383:FOXJ:Forkhead,AC0384:FOXO/FOXJ:Forkhead,AC0385:FOXC/TBP:Forkhead,AC0386:FOXR:Forkhead,AC0387:FOXA/FOXO:Forkhead,"AC0388:ZKSCAN:C2H2_ZF,MADF",AC0389:FOXN:Forkhead,AC0390:CREB/JUND:bZIP,AC0391:FOXN:Forkhead,AC0393:IRX:Homeodomain,"AC0394:PAX:Homeodomain,Paired_box",AC0395:SOX:Sox,"AC0396:POU2F:Homeodomain,POU","AC0397:POU2F/POU3F:Homeodomain,POU",AC0398:POU6F:Homeodomain,AC0399:FOXL:['Fork_head/winged_helix_factors'],AC0400:GMEB:SAND,AC0401:GMEB:SAND,AC0402:CEBPB/CEBPE:bZIP,AC0403:DBP/HLF:bZIP,AC0404:TIGD:CENPB,AC0405:ZNF:C2H2_ZF,AC0406:ZNF:C2H2_ZF,AC0407:RXRG/RARB:Nuclear_receptor,AC0408:RORC/RORA:Nuclear_receptor,AC0409:NR2E:Nuclear_receptor,AC0410:RARA/RARG:Nuclear_receptor,AC0411:NR1I/VDR:Nuclear_receptor,AC0412:NR1I/NR1H:Nuclear_receptor,AC0413:THRB/RARA:Nuclear_receptor,AC0414:NR4A/NR2C:Nuclear_receptor,AC0415:RARA/ESRRA:Nuclear_receptor,AC0416:RXRA/NR2C:Nuclear_receptor,AC0417:NR2E:Nuclear_receptor,AC0418:ZNF:C2H2_ZF,AC0419:ESR/ESRRA:Nuclear_receptor,AC0420:THRA/THRB:Nuclear_receptor,AC0421:THRB:Nuclear_receptor,AC0422:ESRRA/NR5A:Nuclear_receptor,AC0423:NR2E:Nuclear_receptor,AC0424:NR4A:Nuclear_receptor,AC0425:NR2E:Nuclear_receptor,AC0426:HNF4A/ZNF:Nuclear_receptor,AC0427:NR6A:Nuclear_receptor,AC0428:NKX:Homeodomain,AC0429:GLI:C2H2_ZF,AC0430:TCF7L/LEF:Sox,AC0431:LEF:Sox,AC0432:BCL11A/BCL11B:C2H2_ZF,AC0433:HNF4A/HNF4G:Nuclear_receptor,AC0434:NR2F/RXRG:Nuclear_receptor,AC0435:ZNF:C2H2_ZF,AC0436:BPTF/FOXC:Unknown,AC0437:CEBPA:bZIP,AC0438:HSF:HSF,AC0439:ZNF/DMRT:C2H2_ZF,"AC0440:POU3F/GFI:Homeodomain,POU",AC0441:WT/HOXB:Homeodomain,AC0442:ZNF:C2H2_ZF,AC0443:CTCF/ZNF:C2H2_ZF,AC0444:ZNF:C2H2_ZF,AC0445:ZNF:C2H2_ZF,AC0446:ZNF:C2H2_ZF,AC0447:ZFP:C2H2_ZF,AC0448:ZNF:C2H2_ZF,AC0449:ZNF:C2H2_ZF,AC0450:FEZF:C2H2_ZF,AC0451:ZNF:C2H2_ZF,AC0452:ZNF354A/ZNF:C2H2_ZF,AC0453:ZNF:C2H2_ZF,AC0454:ZNF:C2H2_ZF,AC0455:NFATC/PRDM:Rel,AC0456:ZNF/PRDM:C2H2_ZF,AC0457:ZNF/ZFP:C2H2_ZF,AC0458:ZFP:C2H2_ZF,AC0459:ZNF:C2H2_ZF,AC0460:ZNF:C2H2_ZF,AC0461:ZNF:C2H2_ZF,AC0462:ZNF:C2H2_ZF,AC0463:ZNF:C2H2_ZF,AC0464:ZNF:C2H2_ZF,AC0465:ZIK:C2H2_ZF,AC0466:ZNF:C2H2_ZF,"AC0467:PAX:Homeodomain,Paired_box",AC0468:ZNF780A:C2H2_ZF,AC0469:ZNF:C2H2_ZF,AC0470:ZNF:C2H2_ZF,AC0471:ZNF:C2H2_ZF,AC0472:ZNF:C2H2_ZF,AC0473:ZNF:C2H2_ZF,AC0474:ZNF:C2H2_ZF,AC0475:ZNF:C2H2_ZF,AC0476:THAP:THAP_finger,AC0477:ZNF:C2H2_ZF,AC0478:ZNF/PAX:C2H2_ZF,"AC0479:PAX:Homeodomain,Paired_box",AC0480:ZFP:C2H2_ZF,AC0481:ZNF:C2H2_ZF,AC0482:ZNF:C2H2_ZF,AC0483:ZNF:C2H2_ZF,AC0484:ZNF:C2H2_ZF,AC0485:ZNF:C2H2_ZF,AC0486:ZFP/ZFP69B:C2H2_ZF,AC0487:ZNF:C2H2_ZF,AC0488:ZNF:C2H2_ZF,AC0489:ZNF:C2H2_ZF,AC0490:ZNF:C2H2_ZF,AC0491:ZNF:C2H2_ZF,AC0492:ZNF:C2H2_ZF,AC0493:ZNF:C2H2_ZF,AC0494:ZNF:C2H2_ZF,AC0495:ZNF:C2H2_ZF,AC0496:ZNF:C2H2_ZF,AC0497:ZNF:C2H2_ZF,AC0498:ZNF:C2H2_ZF,AC0499:ZBTB:C2H2_ZF,AC0500:ZNF:C2H2_ZF,AC0501:ZNF:C2H2_ZF,AC0502:ZNF:C2H2_ZF,AC0503:ZNF:C2H2_ZF,AC0504:ZNF:C2H2_ZF,AC0505:ZNF:C2H2_ZF,AC0506:ZNF:['C2H2_zinc_finger_factors'],AC0507:PAX:Paired_box,AC0508:FOSL:bZIP,AC0509:MBNL:CCCH_ZF,AC0510:ZNF:C2H2_ZF,AC0511:ZNF:C2H2_ZF,AC0512:ZNF:C2H2_ZF,AC0513:NR3C/AR:Nuclear_receptor,AC0514:NR3C/AR:Nuclear_receptor,AC0515:NR3C:Nuclear_receptor,AC0516:ZNF:C2H2_ZF,AC0517:ZNF585A:C2H2_ZF,AC0518:NKX/MSANTD:['Homeo_domain_factors'],AC0519:NKX:Homeodomain,AC0521:ZNF:C2H2_ZF,AC0522:ZKSCAN:C2H2_ZF,AC0523:NKX:Homeodomain,AC0525:NFYA/NFYB:CBF/NF-Y,AC0526:GFI/GFI1B:C2H2_ZF,AC0527:PBX/PKNOX:Homeodomain,AC0528:ANHX:Homeodomain,AC0529:ZNF:C2H2_ZF,AC0530:ZNF:C2H2_ZF,AC0531:ZNF:C2H2_ZF,AC0532:ZNF:C2H2_ZF,"AC0533:POU3F/POU1F:Homeodomain,POU","AC0534:POU3F:Homeodomain,POU","AC0535:POU4F/POU5F:Homeodomain,POU","AC0536:POU3F/POU2F:Homeodomain,POU","AC0537:POU4F:Homeodomain,POU","AC0538:POU3F:Homeodomain,POU",AC0539:IRX:Homeodomain,AC0540:ASCL:bHLH,AC0541:CREB3L/XBP:bZIP,AC0542:ZBTB:C2H2_ZF,AC0543:PROX:Prospero,AC0544:GMEB:SAND,AC0545:CREB:bZIP,AC0546:ZNF:C2H2_ZF,AC0547:ATF/CREB:bZIP,AC0548:NR2E:Nuclear_receptor,AC0549:ZNF:C2H2_ZF,AC0550:HES/EGR:bHLH,AC0551:CREB3L/XBP:bZIP,AC0552:HES/MAX:bHLH,AC0553:ZBTB:C2H2_ZF,AC0554:HIF1A/TCFL:bHLH,AC0555:SREBF:bHLH,AC0556:USF/BHLHE:bHLH,AC0557:PBX/HOXA:Homeodomain,AC0558:HOXB/PBX:Homeodomain,AC0559:MEIS/PBX:Homeodomain,"AC0560:PAX:Homeodomain,Paired_box","AC0561:PAX:Homeodomain,Paired_box","AC0562:PAX:Homeodomain,Paired_box",AC0563:SPDEF:Ets,AC0564:PITX/OTX:Homeodomain,AC0565:ZNF:C2H2_ZF,"AC0566:ZSCAN:C2H2_ZF,MADF",AC0567:HMX/ISL:Homeodomain,AC0568:ZNF:C2H2_ZF,"AC0569:CUX:CUT,Homeodomain",AC0570:TLX:Homeodomain,AC0571:BARHL/MSX:Homeodomain,AC0572:BARHL:Homeodomain,AC0573:ZNF354A/ZNF354B:C2H2_ZF,AC0574:HOXD/FOXC:Homeodomain,AC0575:ZNF:C2H2_ZF,"AC0577:POU2F:Homeodomain,POU",AC0578:LCORL:Pipsqueak,"AC0579:POU3F:Homeodomain,POU",AC0580:VENTX:Homeodomain,AC0581:ZSCAN:C2H2_ZF,AC0582:TBP/HOXD:TBP,AC0583:WT/FOXC:C2H2_ZF,AC0584:DMRT/HOXB:DM,AC0585:HESX/HOXB:Homeodomain,AC0586:ZNF:C2H2_ZF,"AC0587:POU5F/NANOG:Homeodomain,POU","AC0588:POU2F/POU3F:Homeodomain,POU","AC0589:POU2F:Homeodomain,POU",AC0590:HOXC/CDX:Homeodomain,AC0591:HOXA/HOXD:Homeodomain,AC0592:CDX/HOXA:Homeodomain,AC0593:ELK/ETV:Ets,AC0594:HOXC/HOXD:Homeodomain,AC0595:NKX:Homeodomain,AC0596:HOXB/LHX:Homeodomain,AC0597:NKX:Homeodomain,"AC0598:PAX:Homeodomain,Paired_box","AC0599:CUX:CUT,Homeodomain",AC0600:HOMEZ:Homeodomain,"AC0601:ONECUT/CUX:CUT,Homeodomain",AC0602:ZZZ:Myb/SANT,AC0603:ZNF:C2H2_ZF,AC0604:ZNF:C2H2_ZF,AC0605:SCRT:C2H2_ZF,AC0606:SNAI/ZEB:C2H2_ZF,AC0607:OLIG/NEUROG:bHLH,AC0608:TFAP/MYOD:bHLH,AC0609:ZBTB/OLIG:bHLH,AC0610:TCF/ASCL:bHLH,AC0611:NHLH/TFAP:bHLH,AC0612:MEIS/TGIF:Homeodomain,AC0613:MEIS/PKNOX:Homeodomain,AC0614:LHX:Homeodomain,AC0615:ZNF:C2H2_ZF,AC0616:ZNF:C2H2_ZF,AC0617:ERG/FLI:Ets,AC0618:ZNF:C2H2_ZF,AC0619:SPDEF:Ets,AC0620:ZNF:C2H2_ZF,"AC0621:FOXO1::ELK/ERF::FOXO:['Tryptophan_cluster_factors',_'Fork_head/winged_helix_factors']",AC0622:ELF/SPIB:Ets,AC0623:ZNF:C2H2_ZF,AC0624:ZBTB:C2H2_ZF,AC0625:ELF:Ets,AC0626:ELF/ETV:Ets,AC0627:ELF:Ets,AC0628:SMAD:SMAD,AC0629:SMAD:SMAD,AC0630:ZNF:C2H2_ZF,AC0631:T/TBX:T-box,AC0632:TBX/MGA:T-box,AC0633:TBX/MGA::EVX:T-box,AC0634:ZNF:C2H2_ZF,AC0635:TBX/EOMES:T-box,AC0636:SREBF:bHLH,AC0637:AHR:bHLH,BIAS

In [10]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.ori.shap.summary.tsv", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### assign and show
dat_shap_ori_summary = dat
print(dim(dat))
fun_display_table(head(dat))

[1] 629   5

feature,mean_abs_shap,mean_shap,frac_nonzero,rank
AC0526:GFI/GFI1B:C2H2_ZF,0.0059713,-0.0000631,1,1
AC0606:SNAI/ZEB:C2H2_ZF,0.0051458,0.0000143,1,2
AC0403:DBP/HLF:bZIP,0.0035668,0.0006629,1,3
AC0499:ZBTB:C2H2_ZF,0.0017624,-0.0001508,1,4
AC0059:YY/ZFP:C2H2_ZF,0.0015543,0.0000578,1,5
AC0242:FOSL/JUND:bZIP,0.0015541,0.0000552,1,6

In [13]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.dinuc.shap.summary.tsv", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### assign and show
dat_shap_nuc_summary = dat
print(dim(dat))
fun_display_table(head(dat))

[1] 629   5

feature,mean_abs_shap,mean_shap,frac_nonzero,rank
"AC0440:POU3F/GFI:Homeodomain,POU",0.0020416,-0.0005439,1,1
AC0093:ZNF:C2H2_ZF,0.0013839,-0.0000751,1,2
AC0478:ZNF/PAX:C2H2_ZF,0.0011721,-0.0003497,1,3
AC0169:ZNF/PRDM:C2H2_ZF,0.0011140,-0.0001155,1,4
AC0469:ZNF:C2H2_ZF,0.0010908,0.0000886,1,5
AC0041:ZNF:C2H2_ZF,0.0010659,0.0000669,1,6

## Sanity check: SHAP and yhat

In [11]:
## 1) identify bias column (usually last, named "BIAS")
stopifnot("BIAS" %in% colnames(mat_shap_ori_import))
idx_bias <- which(colnames(mat_shap_ori_import) == "BIAS")

## 2) reconstruct predictions from SHAP
vec_bias <- mat_shap_ori_import[, idx_bias]
mat_phi  <- mat_shap_ori_import[, -idx_bias, drop = FALSE]
vec_yhat_recon <- vec_bias + rowSums(mat_phi)

## 3) compare to saved yhat
stopifnot(length(vec_yhat_ori_import) == length(vec_yhat_recon))

diff <- vec_yhat_ori_import - vec_yhat_recon

cat("max_abs_diff =", max(abs(diff)), "\n")
cat("mean_abs_diff =", mean(abs(diff)), "\n")
cat("sd_diff =", sd(diff), "\n")

## optional: inspect a few cases
head(cbind(yhat_saved = vec_yhat_ori_import,
           yhat_recon = vec_yhat_recon,
           diff = diff))

max_abs_diff = 1.789578e-06
mean_abs_diff = 4.964666e-08
sd_diff = 7.879881e-08

     yhat_saved yhat_recon diff
[1,] 0.10188500 0.10188513 -1.328425e-07
[2,] 0.06695375 0.06695373  1.739609e-08
[3,] 0.12258269 0.12258268  1.384427e-08
[4,] 0.06394247 0.06394247 -2.296575e-09
[5,] 0.05081124 0.05081122  2.148082e-08
[6,] 0.05099595 0.05099592  3.420269e-08

Your pipeline is now fully validated:

XGBoost CV training ✔

Final model training ✔

Prediction generation ✔

SHAP computation ✔

SHAP reconstruction check ✔

## Step 1: Global motif importance

In [12]:
### Step 1: Global motif importance
### Goal: Which motifs most influence ΔBlueSTARR predictions?
### Metric: mean(|SHAP|)
### Intepretation:
###   mean(|SHAP|) = global importance
###   Large values mean the motif strongly affects predictions.

### remove bias column
mat_shap = mat_shap_ori_import
idx_bias <- which(colnames(mat_shap) == "BIAS")
mat_phi  <- mat_shap[, -idx_bias]

### compute importance
df_imp <- data.frame(
    motif = colnames(mat_phi),
    mean_abs_shap = colMeans(abs(mat_phi)),
    mean_shap = colMeans(mat_phi)
)

### sort
df_imp <- df_imp[order(-df_imp$mean_abs_shap), ]

head(df_imp, 20)

                                 motif                            mean_abs_shap
AC0526:GFI/GFI1B:C2H2_ZF         AC0526:GFI/GFI1B:C2H2_ZF         0.0059712606
AC0606:SNAI/ZEB:C2H2_ZF          AC0606:SNAI/ZEB:C2H2_ZF          0.0051457606
AC0403:DBP/HLF:bZIP              AC0403:DBP/HLF:bZIP              0.0035667802
AC0499:ZBTB:C2H2_ZF              AC0499:ZBTB:C2H2_ZF              0.0017623873
AC0059:YY/ZFP:C2H2_ZF            AC0059:YY/ZFP:C2H2_ZF            0.0015543497
AC0242:FOSL/JUND:bZIP            AC0242:FOSL/JUND:bZIP            0.0015540667
AC0626:ELF/ETV:Ets               AC0626:ELF/ETV:Ets               0.0015530736
AC0478:ZNF/PAX:C2H2_ZF           AC0478:ZNF/PAX:C2H2_ZF           0.0014947108
AC0060:YY/MZF:C2H2_ZF            AC0060:YY/MZF:C2H2_ZF            0.0013566747
AC0440:POU3F/GFI:Homeodomain,POU AC0440:POU3F/GFI:Homeodomain,POU 0.0012667683
AC0093:ZNF:C2H2_ZF               AC0093:ZNF:C2H2_ZF               0.0011825585
AC0322:ZNF:C2H2_ZF               AC0322:ZNF:C2H2_ZF               0.0011370805
AC0547:ATF/CREB:bZIP             AC0547:ATF/CREB:bZIP             0.0011016961
AC0194:ZNF:C2H2_ZF               AC0194:ZNF:C2H2_ZF               0.0009284229
AC0390:CREB/JUND:bZIP            AC0390:CREB/JUND:bZIP            0.0009252499
AC0172:ZNF:C2H2_ZF               AC0172:ZNF:C2H2_ZF               0.0008914687
AC0213:STAT/STAT5A:STAT          AC0213:STAT/STAT5A:STAT          0.0008450621
AC0202:ZNF:C2H2_ZF               AC0202:ZNF:C2H2_ZF               0.0008361814
AC0247:ZNF:C2H2_ZF               AC0247:ZNF:C2H2_ZF               0.0008330485
AC0610:TCF/ASCL:bHLH             AC0610:TCF/ASCL:bHLH             0.0008102131
                                 mean_shap
AC0526:GFI/GFI1B:C2H2_ZF         -6.313160e-05
AC0606:SNAI/ZEB:C2H2_ZF           1.428257e-05
AC0403:DBP/HLF:bZIP               6.628760e-04
AC0499:ZBTB:C2H2_ZF              -1.508110e-04
AC0059:YY/ZFP:C2H2_ZF             5.780960e-05
AC0242:FOSL/JUND:bZIP             5.521467e-05
AC0626:ELF/ETV:Ets                1.047255e-04
AC0478:ZNF/PAX:C2H2_ZF            1.114525e-04
AC0060:YY/MZF:C2H2_ZF            -2.892561e-05
AC0440:POU3F/GFI:Homeodomain,POU  9.255149e-05
AC0093:ZNF:C2H2_ZF               -5.759948e-05
AC0322:ZNF:C2H2_ZF               -2.578862e-05
AC0547:ATF/CREB:bZIP             -8.792596e-05
AC0194:ZNF:C2H2_ZF                1.220814e-05
AC0390:CREB/JUND:bZIP            -7.525733e-05
AC0172:ZNF:C2H2_ZF               -4.888785e-05
AC0213:STAT/STAT5A:STAT          -1.521956e-05
AC0202:ZNF:C2H2_ZF               -6.467697e-06
AC0247:ZNF:C2H2_ZF                1.851768e-06
AC0610:TCF/ASCL:bHLH             -7.963996e-06

## Step 2: Directionality of motif effects

In [12]:
### Step 2: Directionality of motif effects
### Goal: Does the motif tend to increase or decrease ΔBlueSTARR?
### Metric: mean(SHAP)
### Add interpretation:
###   mean_SHAP > 0   → activating motif
###   mean_SHAP < 0   → repressing motif

### sort by mean_SHAP > 0
df_imp <- df_imp[order(-df_imp$mean_shap), ]
fun_display_table(head(df_imp, 20))

### sort by mean_SHAP < 0
df_imp <- df_imp[order(df_imp$mean_shap), ]
fun_display_table(head(df_imp, 20))

,motif,mean_abs_shap,mean_shap
AC0403:DBP/HLF:bZIP,AC0403:DBP/HLF:bZIP,0.0035668,0.0006629
AC0478:ZNF/PAX:C2H2_ZF,AC0478:ZNF/PAX:C2H2_ZF,0.0014947,0.0001115
AC0626:ELF/ETV:Ets,AC0626:ELF/ETV:Ets,0.0015531,0.0001047
"AC0440:POU3F/GFI:Homeodomain,POU","AC0440:POU3F/GFI:Homeodomain,POU",0.0012668,0.0000926
AC0044:ZNF:C2H2_ZF,AC0044:ZNF:C2H2_ZF,0.0004718,0.0000767
AC0169:ZNF/PRDM:C2H2_ZF,AC0169:ZNF/PRDM:C2H2_ZF,0.0005127,0.0000685
AC0059:YY/ZFP:C2H2_ZF,AC0059:YY/ZFP:C2H2_ZF,0.0015543,0.0000578
AC0242:FOSL/JUND:bZIP,AC0242:FOSL/JUND:bZIP,0.0015541,0.0000552
AC0611:NHLH/TFAP:bHLH,AC0611:NHLH/TFAP:bHLH,0.0005012,0.0000413
AC0556:USF/BHLHE:bHLH,AC0556:USF/BHLHE:bHLH,0.0002550,0.0000294
AC0006:MEOX:Homeodomain,AC0006:MEOX:Homeodomain,0.0001581,0.0000289
AC0002:PROP/ALX:Homeodomain,AC0002:PROP/ALX:Homeodomain,0.0002483,0.0000282
AC0519:NKX:Homeodomain,AC0519:NKX:Homeodomain,0.0002033,0.0000252
AC0622:ELF/SPIB:Ets,AC0622:ELF/SPIB:Ets,0.0004709,0.0000237
AC0241:NFE2L/JUN:bZIP,AC0241:NFE2L/JUN:bZIP,0.0008028,0.0000236
AC0586:ZNF:C2H2_ZF,AC0586:ZNF:C2H2_ZF,0.0004691,0.0000223
AC0084:HIC:C2H2_ZF,AC0084:HIC:C2H2_ZF,0.0006581,0.0000201
AC0098:ZNF:C2H2_ZF,AC0098:ZNF:C2H2_ZF,0.0003417,0.0000184
AC0042:ZSCAN:C2H2_ZF,AC0042:ZSCAN:C2H2_ZF,0.0001714,0.0000183
AC0510:ZNF:C2H2_ZF,AC0510:ZNF:C2H2_ZF,0.0003580,0.0000171

,motif,mean_abs_shap,mean_shap
AC0499:ZBTB:C2H2_ZF,AC0499:ZBTB:C2H2_ZF,0.0017624,-0.0001508
AC0547:ATF/CREB:bZIP,AC0547:ATF/CREB:bZIP,0.0011017,-0.0000879
AC0402:CEBPB/CEBPE:bZIP,AC0402:CEBPB/CEBPE:bZIP,0.0006791,-0.0000862
AC0390:CREB/JUND:bZIP,AC0390:CREB/JUND:bZIP,0.0009252,-0.0000753
AC0526:GFI/GFI1B:C2H2_ZF,AC0526:GFI/GFI1B:C2H2_ZF,0.0059713,-0.0000631
AC0544:GMEB:SAND,AC0544:GMEB:SAND,0.0007192,-0.0000627
AC0093:ZNF:C2H2_ZF,AC0093:ZNF:C2H2_ZF,0.0011826,-0.0000576
AC0172:ZNF:C2H2_ZF,AC0172:ZNF:C2H2_ZF,0.0008915,-0.0000489
AC0233:HINFP:['C2H2_zinc_finger_factors'],AC0233:HINFP:['C2H2_zinc_finger_factors'],0.0002877,-0.0000366
AC0461:ZNF:C2H2_ZF,AC0461:ZNF:C2H2_ZF,0.0004724,-0.0000349
AC0214:OSR:C2H2_ZF,AC0214:OSR:C2H2_ZF,0.0002943,-0.0000323
AC0450:FEZF:C2H2_ZF,AC0450:FEZF:C2H2_ZF,0.0002128,-0.0000320
AC0014:BATF/FOSL:bZIP,AC0014:BATF/FOSL:bZIP,0.0002104,-0.0000313
AC0060:YY/MZF:C2H2_ZF,AC0060:YY/MZF:C2H2_ZF,0.0013567,-0.0000289
AC0322:ZNF:C2H2_ZF,AC0322:ZNF:C2H2_ZF,0.0011371,-0.0000258
AC0417:NR2E:Nuclear_receptor,AC0417:NR2E:Nuclear_receptor,0.0004872,-0.0000249
AC0574:HOXD/FOXC:Homeodomain,AC0574:HOXD/FOXC:Homeodomain,0.0002302,-0.0000240
AC0255:GATA:GATA,AC0255:GATA:GATA,0.0003985,-0.0000230
AC0173:ZNF:C2H2_ZF,AC0173:ZNF:C2H2_ZF,0.0004647,-0.0000223
AC0498:ZNF:C2H2_ZF,AC0498:ZNF:C2H2_ZF,0.0003514,-0.0000221

## Step 3 — compare SHAP importance vs enrichment

logistic enrichment odds ratio
vs
mean(|SHAP|)

Motifs that are high in both are strong GOF drivers.

## Step 4 — motif gain/loss SHAP analysis

Use the method we discussed earlier:  
gain motifs → positive SHAP  
loss motifs → negative SHAP

```
dat_shap_ori_summary <- dat_shap_ori_summary |> dplyr::rename(motif = feature)
dat_shap_nuc_summary <- dat_shap_nuc_summary |> dplyr::rename(motif = feature)

df_merge <- merge(dat_shap_ori_summary, dat_shap_nuc_summary, by="motif",
                  suffixes=c("_ori","_dinuc"))
```

In [20]:
df_merge <- merge(
    dat_shap_ori_summary,
    dat_shap_nuc_summary,
    by = "feature",
    suffixes = c("_ori", "_dinuc")
)

df_merge$delta_importance =
    df_merge$mean_abs_shap_ori -
    df_merge$mean_abs_shap_dinuc

df_merge <- df_merge[order(-df_merge$delta_importance), ]
fun_display_table(head(df_merge))

,feature,mean_abs_shap_ori,mean_shap_ori,frac_nonzero_ori,rank_ori,mean_abs_shap_dinuc,mean_shap_dinuc,frac_nonzero_dinuc,rank_dinuc,delta_importance
519,AC0526:GFI/GFI1B:C2H2_ZF,0.0059713,-0.0000631,1,1,0.0004000,-5.60e-06,1,25,0.0055712
598,AC0606:SNAI/ZEB:C2H2_ZF,0.0051458,0.0000143,1,2,0.0002871,-4.40e-06,1,43,0.0048587
398,AC0403:DBP/HLF:bZIP,0.0035668,0.0006629,1,3,0.0000047,2.70e-06,1,544,0.0035620
240,AC0242:FOSL/JUND:bZIP,0.0015541,0.0000552,1,6,0.0000668,-4.00e-07,1,244,0.0014872
494,AC0499:ZBTB:C2H2_ZF,0.0017624,-0.0001508,1,4,0.0003092,-1.43e-05,1,37,0.0014532
59,AC0059:YY/ZFP:C2H2_ZF,0.0015543,0.0000578,1,5,0.0001497,-1.00e-06,1,126,0.0014046

In [17]:
### Step 4 — Variant-level interpretation
### Goal: Which motifs drive predictions for each variant?
### Intepretation:
#### positive SHAP → motif increases ΔBlueSTARR
### negative SHAP → motif decreases ΔBlueSTARR
i <- 100

shap_vec <- mat_phi[i, ]

top_motifs <- sort(shap_vec, decreasing = TRUE)[1:10]
print(top_motifs)

       AC0060:YY/MZF:C2H2_ZF           AC0488:ZNF:C2H2_ZF
                 0.080286667                  0.046478428
           AC0061:YY:C2H2_ZF               AC0087:E2F:E2F
                 0.034325946                  0.033941399
           AC0404:TIGD:CENPB           AC0449:ZNF:C2H2_ZF
                 0.031867001                  0.012892098
          AC0454:ZNF:C2H2_ZF               AC0159:E2F:E2F
                 0.011870677                  0.010046356
          AC0262:SOX/SRY:Sox AC0432:BCL11A/BCL11B:C2H2_ZF
                 0.009819797                  0.009514230

Part 2 — The powerful step
Motif gain / loss interpreted through SHAP

This is where your pipeline becomes very strong scientifically.

You already computed:

motifdelta gain/loss events

for each variant.

So now we connect:

motif perturbation  →  SHAP effect
Conceptual framework

For each variant:

motifdelta gives:
    motif gained
    motif lost

SHAP gives:

motif contribution to prediction

So we test:

gained motif → positive SHAP
lost motif   → negative SHAP

This directly tests the mechanism:

motif perturbation drives GOF prediction

Conceptual framework

For each variant:

motifdelta gives:
    motif gained
    motif lost

SHAP gives:

motif contribution to prediction

So we test:

gained motif → positive SHAP
lost motif   → negative SHAP

This directly tests the mechanism:

motif perturbation drives GOF prediction

Step 5 — Prepare motif gain/loss table

Step 6 — join with SHAP

Convert SHAP matrix to long format:

In [19]:
df_shap <- as.data.frame(mat_phi)
df_shap$variant_id <- rownames(df_shap)

df_shap_long <- pivot_longer(
    df_shap,
    cols = -variant_id,
    names_to = "motif",
    values_to = "shap"
)

In [20]:
df_join <- merge(
    df_shap_long,
    df_motifdelta,
    by = c("variant_id", "motif")
)

ERROR: Error: object 'df_motifdelta' not found

Now each row contains:

variant
motif
event (gain/loss)
SHAP value

Step 7 — test gain vs loss effect

In [21]:
aggregate(shap ~ event, df_join, mean)
boxplot(shap ~ event, data = df_join)

ERROR: Error in eval(m$data, parent.frame()): object 'df_join' not found

Step 8 — motif-specific analysis
aggregate(shap ~ motif + event, df_join, mean)

Step 9 — enrichment of gain motifs in top GOF variants

Define top variants:

top 5% ΔBlueSTARR

Then test:

motif gain frequency

This links:

model prediction
motif perturbation
biological mechanism

Part 3 — Why this analysis is powerful

Most ML papers stop at:

SHAP importance

But your analysis connects:

motifdelta (mechanistic perturbation)
+
SHAP (model interpretation)
+
variant prediction (ΔBlueSTARR)

This creates a causal narrative:

variant → motif gain → increased regulatory activity

That is exactly what reviewers want to see.


If you want, I can also show you

Two analyses that would make your paper much stronger:

1️⃣ Motif interaction networks from SHAP

Identify cooperative TF modules.

2️⃣ Variant clustering using SHAP vectors

Identify mechanistic classes of GOF variants.

Both analyses work extremely well with your dataset size (~200k variants) and would integrate beautifully with your UMAP / clustering work from FCC.

Excellent question. You are now at the interpretation stage, and these two analyses can indeed make the story much stronger if done carefully.

I will walk you through practical, implementable workflows that fit your current pipeline:

You already have:

mat_shap_ori (199971 × 629)

mat_shap_dinuc

motifdelta gain/loss table

predicted ΔBlueSTARR

So the next analyses are pure downstream analysis, no retraining required.

Motif interaction networks from SHAP

Goal:

Identify TF motifs that act together to drive regulatory activity.

Biological interpretation:

GATA1 + TAL1 → erythroid enhancer module
AP1 + ETS → immune enhancer module

This reveals cooperative TF modules.

Core idea

Two motifs interact if their SHAP contributions co-vary across variants.

Mathematically:

correlation( SHAP_motif_A , SHAP_motif_B )

High positive correlation means:

variants activating motif A also activate motif B

Which often reflects TF co-binding modules.

Step 1 — remove bias column
idx_bias <- which(colnames(mat_shap_ori) == "BIAS")
mat_phi <- mat_shap_ori[, -idx_bias]
Step 2 — compute motif correlation matrix

Since you have ~629 motifs:

629 × 629 matrix

This is small.

mat_cor <- cor(mat_phi)

If memory is tight:

mat_cor <- cor(mat_phi, method="pearson")
Step 3 — keep strong interactions

Example threshold:

thr <- 0.3

Convert to edge list:

library(reshape2)

df_edges <- melt(mat_cor)
colnames(df_edges) <- c("motif1","motif2","cor")

df_edges <- subset(df_edges, motif1 != motif2)
df_edges <- subset(df_edges, abs(cor) > thr)
Step 4 — build network
library(igraph)

g <- graph_from_data_frame(df_edges)

Plot:

plot(g)

Step 5 — identify TF modules

Use clustering:

cl <- cluster_louvain(g)

Each cluster = TF regulatory module.

Example result:

cluster 1: GATA1 TAL1 KLF1
cluster 2: AP1 JUN FOS
cluster 3: CTCF RAD21

This becomes a very nice figure in the paper.

Interpretation example

You could write:

SHAP interaction analysis revealed clusters of transcription factor motifs with highly correlated contributions across variants, corresponding to known regulatory modules including erythroid factors (GATA1–TAL1–KLF1) and AP-1 family factors.

Optional improvement (recommended)

Filter motifs by importance first:

top_motifs <- df_shap_summary$motif[1:150]
mat_phi_small <- mat_phi[, top_motifs]

Then compute correlation.

This removes noisy motifs.

2️⃣ Variant clustering using SHAP vectors

Goal:

Identify mechanistic classes of variants.

Instead of grouping variants by genomic location, we group them by motif perturbation mechanism.

Each variant has a 629-dimensional SHAP vector:

variant_i → SHAP across motifs

Variants with similar SHAP profiles share similar regulatory mechanisms.

Step 1 — reduce dimensionality

Use PCA first.

mat_pca <- prcomp(mat_phi, center=TRUE, scale.=TRUE)

mat_pc <- mat_pca$x[,1:20]

20 PCs usually capture most signal.

Step 2 — run UMAP
library(uwot)

umap_emb <- umap(mat_pc)

Now you have:

199k × 2 embedding
Step 3 — cluster variants

Use Leiden or k-means.

Example:

set.seed(1)
cl <- kmeans(mat_pc, centers=10)

Add cluster labels.

Step 4 — interpret clusters

For each cluster compute mean SHAP:

cluster_mean <- aggregate(mat_phi, list(cluster=cl$cluster), mean)

Then identify dominant motifs:

cluster 1 → GATA1
cluster 2 → AP1
cluster 3 → CTCF loss

So clusters represent distinct GOF mechanisms.

Step 5 — visualize

Plot UMAP:

UMAP colored by cluster

Then label clusters with top motifs.

Example figure:

Cluster A: GATA1 gain variants
Cluster B: AP1 activation variants
Cluster C: CTCF loss variants
3️⃣ Combine with motifdelta

This is where your study becomes very compelling.

For each variant cluster:

Compute motifdelta gain frequency.

Example:

This demonstrates:

SHAP cluster ↔ motif perturbation mechanism