---
title: Variant results from Richard 02
subtitle: Explore tables 
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [1]:
suppressMessages(suppressWarnings(source("../run_config_project.R")))
suppressMessages(suppressWarnings(library("xgboost")))
suppressMessages(suppressWarnings(library("Matrix")))
show_env()

BASE DIRECTORY (FD_BASE): /hpc/group/igvf/kk319
REPO DIRECTORY (FD_REPO): /hpc/group/igvf/kk319/repo
WORK DIRECTORY (FD_WORK): /hpc/group/igvf/kk319/work
DATA DIRECTORY (FD_DATA): /hpc/group/igvf/kk319/data

You are working with      IGVF BlueSTARR
PATH OF PROJECT (FD_PRJ): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR
PROJECT RESULTS (FD_RES): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/results
PROJECT SCRIPTS (FD_EXE): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/scripts
PROJECT DATA    (FD_DAT): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/data
PROJECT NOTE    (FD_NBK): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/notebooks
PROJECT DOCS    (FD_DOC): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/docs
PROJECT LOG     (FD_LOG): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/log
PROJECT REF     (FD_REF): /hpc/group/igvf/kk319/repo/Proj_IGVF_BlueSTARR/references

## Import data

**Check file existence**

In [2]:
### set file directory
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)

vec = dir(txt_fdiry)
for (txt in vec){cat(txt, "\n")}

variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.nuc.X.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.ori.X.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.xgb_cv.rds
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.xgb_model.bin
variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs.pilot.y.rds

### Import data

In [3]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.y.rds", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
obj = read_rds(txt_fpath)

### assign and show
vec_y_ori_import = obj
print(length(obj))
print(head(obj))

[1] 199971
chr1:100186033:T:T:A chr1:100306767:A:A:C chr1:100307737:G:G:C
           0.1147592            0.1031407            0.1006881
chr1:100324154:G:G:C chr1:100520609:T:C:G chr1:100521850:A:A:T
           0.0812454            0.1144301            0.1018046

In [4]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.ori.X.rds", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_rds(txt_fpath)

### assign and show
mat_event_ori_import = dat
print(dim(dat))
fun_display_table(head(dat[,1:6], 3))

[1] 199971    629

,AC0001:GATA/PROP:GATA,AC0002:PROP/ALX:Homeodomain,AC0003:HNF1A/HNF1B:Homeodomain,AC0004:ZSCAN:C2H2_ZF,"AC0005:POU3F/POU1F:Homeodomain,POU",AC0006:MEOX:Homeodomain
chr1:100186033:T:T:A,0,0,0,0,0,0
chr1:100306767:A:A:C,0,0,0,0,0,0
chr1:100307737:G:G:C,0,0,0,0,0,0

In [5]:
### set file directory
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)
txt_fname  = paste(txt_prefix, "pilot.nuc.X.rds", sep = ".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

### read table
dat = read_rds(txt_fpath)

### assign and show
mat_event_nuc_import = dat
print(dim(dat))
fun_display_table(head(dat[,1:6], 3))

[1] 199971    629

,AC0001:GATA/PROP:GATA,AC0002:PROP/ALX:Homeodomain,AC0003:HNF1A/HNF1B:Homeodomain,AC0004:ZSCAN:C2H2_ZF,"AC0005:POU3F/POU1F:Homeodomain,POU",AC0006:MEOX:Homeodomain
chr1:100186033:T:T:A,0,0,0,0,0,0
chr1:100306767:A:A:C,0,0,0,0,0,0
chr1:100307737:G:G:C,0,0,0,0,0,0

## Prepare

**Convert X to sparse**

In [6]:
### convert to sparse dgCMatrix
mat_X_ori = mat_event_ori_import
mat_X_nuc = mat_event_nuc_import
vec_y     = vec_y_ori_import

mat_X_sparse_ori = Matrix::Matrix(mat_X_ori, sparse = TRUE)
mat_X_sparse_nuc = Matrix::Matrix(mat_X_nuc, sparse = TRUE)

### check and remove matrix to save memory
stopifnot(nrow(mat_X_sparse_ori) == length(vec_y))
stopifnot(nrow(mat_X_sparse_nuc) == length(vec_y))
rm(mat_event_ori_import)
rm(mat_event_nuc_import)
gc()

### show results
mat = mat_X_sparse_ori
print(class(mat))
print(dim(mat))
mat = mat_X_sparse_nuc
print(class(mat))
print(dim(mat))

       used      (Mb)   gc trigger (Mb)   max used  (Mb)
Ncells   2539121  135.7   4218671   225.4   4218671  225.4
Vcells 269839806 2058.8 372758007  2844.0 271711366 2073.0

[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
[1] 199971    629
[1] "dgCMatrix"
attr(,"package")
[1] "Matrix"
[1] 199971    629

**Build DMatrix**

In [7]:
dtrain_ori = xgboost::xgb.DMatrix(
    data  = mat_X_sparse_ori,
    label = vec_y
)

dtrain_nuc = xgboost::xgb.DMatrix(
    data  = mat_X_sparse_nuc,
    label = vec_y
)

## Cross-validation

**Define parameters**

In [ ]:
param = list(
    objective        = "reg:squarederror",
    eval_metric      = "rmse",
    max_depth        = 6,
    eta              = 0.1,
    subsample        = 0.8,
    colsample_bytree = 0.8,
    nthread          = 8
)

**Original sequence**

In [7]:
### start timer
time_start = Sys.time()

### init seed
set.seed(123)

fit_xgb_ori_cv = xgboost::xgb.cv(
    params = param,
    data   = dtrain_ori,
    nrounds = 3000,
    nfold   = 5,
    early_stopping_rounds = 50,
    verbose = 0
)

### end timer
time_end = Sys.time()

### print elapsed time
print(time_end - time_start)

Time difference of 26.44866 mins

**Dinuc shuffle sequence**

In [ ]:
### start timer
time_start = Sys.time()

### init seed
set.seed(123)

fit_xgb_nuc_cv = xgboost::xgb.cv(
    params = param,
    data   = dtrain_nuc,
    nrounds = 3000,
    nfold   = 5,
    early_stopping_rounds = 50,
    verbose = 0
)

### end timer
time_end = Sys.time()

### print elapsed time
print(time_end - time_start)

In [8]:
### assign and show
best_iter = fit_xgb_cv$best_iteration
best_test_rmse = fit_xgb_cv$evaluation_log$test_rmse_mean[best_iter]
print(best_iter)
print(best_test_rmse)

vec = fit_xgb_cv$evaluation_log
print(head(vec, 100))
cat("\n")
print(tail(vec, 100))

[1] 2568
[1] 0.05646075
      iter train_rmse_mean train_rmse_std test_rmse_mean test_rmse_std
     <num>           <num>          <num>          <num>         <num>
  1:     1      0.40139255   4.600811e-05     0.40141733  0.0002136557
  2:     2      0.36238194   3.396629e-05     0.36243152  0.0002129574
  3:     3      0.32739716   3.198234e-05     0.32748243  0.0001985589
  4:     4      0.29601790   2.804590e-05     0.29613950  0.0002136397
  5:     5      0.26790404   2.042242e-05     0.26807141  0.0002056657
  6:     6      0.24272160   1.188340e-05     0.24293636  0.0002065968
  7:     7      0.22020287   1.292459e-05     0.22047750  0.0002106083
  8:     8      0.20009010   3.123287e-05     0.20042849  0.0002186316
  9:     9      0.18217461   4.262035e-05     0.18258122  0.0002357375
 10:    10      0.16621529   4.701223e-05     0.16670456  0.0002458223
 11:    11      0.15205252   5.752425e-05     0.15261470  0.0002670482
 12:    12      0.13950129   7.499411e-05     0.14015309  0.0002792085
 13:    13      0.12842872   6.943145e-05     0.12917457  0.0003068419
 14:    14      0.11866321   8.210531e-05     0.11951257  0.0003300485
 15:    15      0.11010391   9.616872e-05     0.11107382  0.0003543765
 16:    16      0.10261515   1.267748e-04     0.10369652  0.0003841336
 17:    17      0.09609831   1.335786e-04     0.09729880  0.0004233927
 18:    18      0.09043967   1.455453e-04     0.09176838  0.0004576449
 19:    19      0.08556248   1.468615e-04     0.08700746  0.0004941779
 20:    20      0.08135947   1.583015e-04     0.08293306  0.0005341845
 21:    21      0.07777424   1.622712e-04     0.07946448  0.0005717896
 22:    22      0.07470589   1.678353e-04     0.07650553  0.0005921804
 23:    23      0.07210773   1.851238e-04     0.07401242  0.0006210612
 24:    24      0.06989839   1.762538e-04     0.07190441  0.0006534819
 25:    25      0.06802712   1.873360e-04     0.07012562  0.0006729885
 26:    26      0.06644805   1.981345e-04     0.06864344  0.0006953454
 27:    27      0.06512102   1.957489e-04     0.06739006  0.0007319138
 28:    28      0.06398881   1.926302e-04     0.06633106  0.0007481991
 29:    29      0.06303222   1.977428e-04     0.06544897  0.0007632930
 30:    30      0.06222381   2.014497e-04     0.06471323  0.0007893086
 31:    31      0.06152761   2.171110e-04     0.06408009  0.0008037242
 32:    32      0.06094429   2.116682e-04     0.06356029  0.0008198646
 33:    33      0.06044197   2.138572e-04     0.06311560  0.0008366917
 34:    34      0.06001339   2.240591e-04     0.06274043  0.0008497362
 35:    35      0.05964021   2.273031e-04     0.06241237  0.0008665110
 36:    36      0.05929912   2.226537e-04     0.06212657  0.0008665292
 37:    37      0.05901345   2.127586e-04     0.06188977  0.0008812312
 38:    38      0.05875396   2.119644e-04     0.06168306  0.0008915426
 39:    39      0.05852464   2.054668e-04     0.06150348  0.0008946408
 40:    40      0.05831773   2.036298e-04     0.06134046  0.0009034647
 41:    41      0.05814043   2.028289e-04     0.06120544  0.0009182725
 42:    42      0.05797854   2.140631e-04     0.06108398  0.0009184247
 43:    43      0.05782566   2.093520e-04     0.06097504  0.0009155933
 44:    44      0.05767277   2.122378e-04     0.06087070  0.0009184623
 45:    45      0.05753821   2.196580e-04     0.06077256  0.0009056310
 46:    46      0.05741574   2.282212e-04     0.06067867  0.0008928441
 47:    47      0.05730402   2.207225e-04     0.06061294  0.0008935105
 48:    48      0.05718786   2.282499e-04     0.06053653  0.0008975576
 49:    49      0.05708413   2.309222e-04     0.06046291  0.0008903606
 50:    50      0.05698487   2.257503e-04     0.06039953  0.0008862095
 51:    51      0.05689254   2.220368e-04     0.06034085  0.0008883990
 52:    52      0.05680891   2.200914e-04     0.06027562  0.0008966128
 53:    53      0.05671481   2.107850e-04     0.06020995  0.0008964166
 54:    54      0.05662672   2.048524e-04     0.06015898  0.0008892389
 55:    55      0.05653541   2.076212e-04     0.06009951  0.0008848727
 56:    56      0.05645625   2.128341e-04     0.06003838  0.0008793871
 57:    57      0.05637991   2.141507e-04     0.05998668  0.0008773576
 58:    58      0.05629468   2.152986e-04     0.05993353  0.0008881276
 59:    59      0.05622363   2.102123e-04     0.05989569  0.0008944974
 60:    60      0.05615336   2.160301e-04     0.05984980  0.0008973159
 61:    61      0.05608255   2.188939e-04     0.05980212  0.0008903789
 62:    62      0.05600993   2.171836e-04     0.05976037  0.0008826017
 63:    63      0.05593905   2.189938e-04     0.05971583  0.0008788224
 64:    64      0.05587485   2.240043e-04     0.05967568  0.0008748457
 65:    65      0.05580422   2.187827e-04     0.05963838  0.0008725151
 66:    66      0.05573119   2.149462e-04     0.05959584  0.0008656608
 67:    67      0.05566720   2.229260e-04     0.05956084  0.0008591076
 68:    68      0.05560407   2.171930e-04     0.05952624  0.0008673918
 69:    69      0.05554664   2.192829e-04     0.05949484  0.0008727526
 70:    70      0.05548803   2.182292e-04     0.05946062  0.0008758198
 71:    71      0.05542638   2.267894e-04     0.05943235  0.0008710724
 72:    72      0.05536148   2.116532e-04     0.05940368  0.0008730614
 73:    73      0.05530535   2.061210e-04     0.05937358  0.0008739814
 74:    74      0.05525445   2.029690e-04     0.05934447  0.0008759855
 75:    75      0.05519698   2.034515e-04     0.05931296  0.0008711612
 76:    76      0.05513635   2.085514e-04     0.05928120  0.0008707429
 77:    77      0.05509001   2.087137e-04     0.05925545  0.0008706052
 78:    78      0.05502984   2.051796e-04     0.05922365  0.0008745931
 79:    79      0.05497580   1.982993e-04     0.05919892  0.0008762421
 80:    80      0.05492555   2.018036e-04     0.05917611  0.0008719344
 81:    81      0.05487488   2.008312e-04     0.05914945  0.0008683738
 82:    82      0.05482192   1.990750e-04     0.05911594  0.0008635587
 83:    83      0.05477189   1.907220e-04     0.05909467  0.0008707613
 84:    84      0.05472116   1.939463e-04     0.05906995  0.0008660379
 85:    85      0.05467079   1.953815e-04     0.05904977  0.0008670405
 86:    86      0.05463290   1.858163e-04     0.05902992  0.0008732327
 87:    87      0.05458518   1.941842e-04     0.05900844  0.0008705145
 88:    88      0.05452649   1.921501e-04     0.05898083  0.0008703187
 89:    89      0.05447779   1.862727e-04     0.05895897  0.0008711864
 90:    90      0.05443668   1.929219e-04     0.05893900  0.0008663721
 91:    91      0.05439433   1.912785e-04     0.05891825  0.0008692149
 92:    92      0.05435072   1.930194e-04     0.05889594  0.0008680814
 93:    93      0.05430724   1.889781e-04     0.05887749  0.0008700235
 94:    94      0.05426672   1.884204e-04     0.05885727  0.0008687522
 95:    95      0.05421719   1.859964e-04     0.05883860  0.0008673311
 96:    96      0.05417509   1.840508e-04     0.05882236  0.0008646049
 97:    97      0.05413312   1.833356e-04     0.05880136  0.0008686711
 98:    98      0.05408953   1.895401e-04     0.05877594  0.0008623413
 99:    99      0.05404558   1.923520e-04     0.05875705  0.0008639553
100:   100      0.05401313   1.889135e-04     0.05874301  0.0008685475
      iter train_rmse_mean train_rmse_std test_rmse_mean test_rmse_std

      iter train_rmse_mean train_rmse_std test_rmse_mean test_rmse_std
     <num>           <num>          <num>          <num>         <num>
  1:  2519      0.04556820   0.0005887016     0.05646756  0.0007256881
  2:  2520      0.04556820   0.0005887005     0.05646757  0.0007256873
  3:  2521      0.04556705   0.0005886601     0.05646717  0.0007261045
  4:  2522      0.04556649   0.0005886424     0.05646709  0.0007261912
  5:  2523      0.04556649   0.0005886436     0.05646709  0.0007261621
  6:  2524      0.04556506   0.0005913318     0.05646688  0.0007259110
  7:  2525      0.04556506   0.0005913310     0.05646686  0.0007259420
  8:  2526      0.04556505   0.0005913311     0.05646684  0.0007259599
  9:  2527      0.04556204   0.0005887328     0.05646631  0.0007265956
 10:  2528      0.04556205   0.0005887320     0.05646632  0.0007266148
 11:  2529      0.04556115   0.0005887023     0.05646628  0.0007266230
 12:  2530      0.04555782   0.0005858774     0.05646601  0.0007267219
 13:  2531      0.04555782   0.0005858772     0.05646603  0.0007266880
 14:  2532      0.04555782   0.0005858773     0.05646602  0.0007266917
 15:  2533      0.04555304   0.0005897617     0.05646630  0.0007248527
 16:  2534      0.04555304   0.0005897612     0.05646631  0.0007248667
 17:  2535      0.04555142   0.0005928206     0.05646452  0.0007226228
 18:  2536      0.04554481   0.0005933749     0.05646214  0.0007223764
 19:  2537      0.04554481   0.0005933750     0.05646217  0.0007223444
 20:  2538      0.04554481   0.0005933750     0.05646215  0.0007223656
 21:  2539      0.04554481   0.0005933752     0.05646215  0.0007223577
 22:  2540      0.04554481   0.0005933748     0.05646215  0.0007223413
 23:  2541      0.04554450   0.0005939542     0.05646212  0.0007222993
 24:  2542      0.04554384   0.0005952079     0.05646220  0.0007224127
 25:  2543      0.04554384   0.0005952074     0.05646217  0.0007224319
 26:  2544      0.04554384   0.0005952081     0.05646222  0.0007223971
 27:  2545      0.04554002   0.0005919949     0.05646264  0.0007218868
 28:  2546      0.04554002   0.0005919944     0.05646263  0.0007218918
 29:  2547      0.04554002   0.0005919938     0.05646262  0.0007218886
 30:  2548      0.04553704   0.0005976397     0.05646308  0.0007224769
 31:  2549      0.04553702   0.0005976238     0.05646306  0.0007224861
 32:  2550      0.04553702   0.0005976248     0.05646307  0.0007224984
 33:  2551      0.04553702   0.0005976248     0.05646306  0.0007225044
 34:  2552      0.04553701   0.0005976236     0.05646304  0.0007225237
 35:  2553      0.04553701   0.0005976233     0.05646304  0.0007225155
 36:  2554      0.04553510   0.0005960502     0.05646280  0.0007224768
 37:  2555      0.04553468   0.0005968365     0.05646265  0.0007222963
 38:  2556      0.04553441   0.0005966128     0.05646259  0.0007223621
 39:  2557      0.04553296   0.0005963610     0.05646270  0.0007224629
 40:  2558      0.04553134   0.0005962435     0.05646263  0.0007225298
 41:  2559      0.04553134   0.0005962432     0.05646264  0.0007225207
 42:  2560      0.04553134   0.0005962420     0.05646263  0.0007225062
 43:  2561      0.04553134   0.0005962425     0.05646264  0.0007224948
 44:  2562      0.04553134   0.0005962421     0.05646264  0.0007225042
 45:  2563      0.04553134   0.0005962416     0.05646263  0.0007225026
 46:  2564      0.04552947   0.0005946919     0.05646162  0.0007237239
 47:  2565      0.04552864   0.0005946373     0.05646153  0.0007238314
 48:  2566      0.04552864   0.0005946376     0.05646154  0.0007238165
 49:  2567      0.04552764   0.0005965473     0.05646115  0.0007233324
 50:  2568      0.04552527   0.0005961494     0.05646075  0.0007229901
 51:  2569      0.04552287   0.0005943407     0.05646079  0.0007229169
 52:  2570      0.04552231   0.0005954011     0.05646091  0.0007230918
 53:  2571      0.04552231   0.0005954013     0.05646090  0.0007231012
 54:  2572      0.04552231   0.0005954018     0.05646089  0.0007231250
 55:  2573      0.04552167   0.0005966151     0.05646122  0.0007235445
 56:  2574      0.04551788   0.0005935572     0.05646326  0.0007211346
 57:  2575      0.04551788   0.0005935569     0.05646326  0.0007211191
 58:  2576      0.04551785   0.0005935542     0.05646331  0.0007210797
 59:  2577      0.04551785   0.0005935535     0.05646334  0.0007210804
 60:  2578      0.04551544   0.0005931533     0.05646322  0.0007209750
 61:  2579      0.04551337   0.0005926819     0.05646299  0.0007212123
 62:  2580      0.04551337   0.0005926818     0.05646297  0.0007212419
 63:  2581      0.04551208   0.0005925912     0.05646273  0.0007214917
 64:  2582      0.04551208   0.0005925917     0.05646271  0.0007214678
 65:  2583      0.04551208   0.0005925923     0.05646270  0.0007214694
 66:  2584      0.04551055   0.0005923496     0.05646297  0.0007217006
 67:  2585      0.04551003   0.0005923152     0.05646296  0.0007217251
 68:  2586      0.04551003   0.0005923147     0.05646298  0.0007217051
 69:  2587      0.04551002   0.0005923142     0.05646297  0.0007217069
 70:  2588      0.04551002   0.0005923140     0.05646297  0.0007217082
 71:  2589      0.04550871   0.0005912584     0.05646290  0.0007217829
 72:  2590      0.04550871   0.0005912583     0.05646292  0.0007217661
 73:  2591      0.04550871   0.0005912567     0.05646294  0.0007217257
 74:  2592      0.04550871   0.0005912570     0.05646295  0.0007217176
 75:  2593      0.04550871   0.0005912592     0.05646299  0.0007216874
 76:  2594      0.04550862   0.0005912534     0.05646314  0.0007215245
 77:  2595      0.04550862   0.0005912528     0.05646313  0.0007215245
 78:  2596      0.04550862   0.0005912524     0.05646313  0.0007215122
 79:  2597      0.04550862   0.0005912530     0.05646314  0.0007214983
 80:  2598      0.04550758   0.0005904207     0.05646304  0.0007216179
 81:  2599      0.04550654   0.0005923905     0.05646252  0.0007209493
 82:  2600      0.04550216   0.0005898102     0.05646225  0.0007212906
 83:  2601      0.04550146   0.0005896167     0.05646191  0.0007217090
 84:  2602      0.04549941   0.0005880409     0.05646174  0.0007219385
 85:  2603      0.04549829   0.0005898466     0.05646139  0.0007216588
 86:  2604      0.04549829   0.0005898455     0.05646137  0.0007216612
 87:  2605      0.04549829   0.0005898456     0.05646135  0.0007216886
 88:  2606      0.04549829   0.0005898448     0.05646136  0.0007216715
 89:  2607      0.04549711   0.0005888003     0.05646096  0.0007216122
 90:  2608      0.04549711   0.0005888011     0.05646097  0.0007216171
 91:  2609      0.04549711   0.0005888008     0.05646096  0.0007216525
 92:  2610      0.04549711   0.0005888005     0.05646094  0.0007216799
 93:  2611      0.04549711   0.0005888005     0.05646094  0.0007216766
 94:  2612      0.04549711   0.0005888005     0.05646098  0.0007216328
 95:  2613      0.04549711   0.0005888007     0.05646098  0.0007216184
 96:  2614      0.04549711   0.0005888003     0.05646097  0.0007216048
 97:  2615      0.04549711   0.0005887996     0.05646095  0.0007216305
 98:  2616      0.04549711   0.0005887999     0.05646095  0.0007216278
 99:  2617      0.04549711   0.0005888000     0.05646096  0.0007216336
100:  2618      0.04549711   0.0005887997     0.05646095  0.0007216324
      iter train_rmse_mean train_rmse_std test_rmse_mean test_rmse_std

## Build final model

In [9]:
### start timer
time_start = Sys.time()

best_iter = fit_xgb_cv$best_iteration
fit_xgb_final = xgboost::xgb.train(
    params  = param,
    data    = dtrain,
    nrounds = best_iter,
    verbose = 1
)

### end timer and show elapsed time
time_end = Sys.time()
print(time_end - time_start)

Time difference of 5.98458 mins

In [10]:
### --------------------------------
### save CV result
### --------------------------------
txt_prefix = "variant_closed_gof_bluestarr.flankL35R70.unobs_vs_obs"
txt_folder = "motifmodel_pilot_jvierstra_v2.1beta"
txt_fdiry  = file.path(FD_RES, "analysis_variant_motif_richard", txt_folder)

txt_fname  = paste(txt_prefix, "pilot.xgb_cv.rds", sep=".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

readr::write_rds(fit_xgb_cv, txt_fpath)

In [11]:
### --------------------------------
### save final model
### --------------------------------
txt_fname  = paste(txt_prefix, "pilot.xgb_model.bin", sep=".")
txt_fpath  = file.path(txt_fdiry, txt_fname)

xgboost::xgb.save(fit_xgb_final, txt_fpath)

[1] TRUE

Later import
```
fit_xgb_cv = readr::read_rds(txt_fpath)
fit_xgb_final = xgboost::xgb.load(txt_fpath)
```

**Define Parameters**

In [11]:
param = list(
    objective        = "reg:squarederror",
    eval_metric      = "rmse",
    max_depth        = 6,
    eta              = 0.05,
    subsample        = 0.8,
    colsample_bytree = 0.8,
    nthread          = 8
)

## Cross-validation

In [12]:
### start timer
time_start = Sys.time()

### init seed
set.seed(123)

fit_xgb_cv = xgboost::xgb.cv(
    params = param,
    data   = dtrain,
    nrounds = 2000,
    nfold   = 5,
    early_stopping_rounds = 50,
    verbose = 1
)

### assign and show
best_iter = fit_xgb_cv$best_iteration
print(best_iter)
print(fit_xgb_cv$best_score)

### end timer
time_end = Sys.time()

### print elapsed time
print(time_end - time_start)

[1]	train-rmse:0.423112+0.000049	test-rmse:0.423124+0.000215
Multiple eval metrics are present. Will use test_rmse for early stopping.
Will train until test_rmse hasn't improved in 50 rounds.

[2]	train-rmse:0.402482+0.000042	test-rmse:0.402504+0.000215
[3]	train-rmse:0.382919+0.000039	test-rmse:0.382956+0.000212
[4]	train-rmse:0.364353+0.000027	test-rmse:0.364403+0.000218
[5]	train-rmse:0.346744+0.000025	test-rmse:0.346810+0.000213
[6]	train-rmse:0.330032+0.000022	test-rmse:0.330114+0.000210
[7]	train-rmse:0.314183+0.000022	test-rmse:0.314285+0.000202
[8]	train-rmse:0.299151+0.000015	test-rmse:0.299274+0.000208
[9]	train-rmse:0.284910+0.000017	test-rmse:0.285054+0.000214
[10]	train-rmse:0.271405+0.000020	test-rmse:0.271572+0.000209
[11]	train-rmse:0.258606+0.000022	test-rmse:0.258792+0.000207
[12]	train-rmse:0.246483+0.000022	test-rmse:0.246691+0.000212
[13]	train-rmse:0.235008+0.000016	test-rmse:0.235239+0.000204
[14]	train-rmse:0.224137+0.000016	test-rmse:0.224393+0.000202
[15]	train-rmse:0.213851+0.000020	test-rmse:0.214133+0.000196
[16]	train-rmse:0.204125+0.000030	test-rmse:0.204435+0.000199
[17]	train-rmse:0.194911+0.000032	test-rmse:0.195256+0.000207
[18]	train-rmse:0.186205+0.000037	test-rmse:0.186582+0.000207
[19]	train-rmse:0.177988+0.000041	test-rmse:0.178397+0.000215
[20]	train-rmse:0.170219+0.000042	test-rmse:0.170675+0.000223
[21]	train-rmse:0.162881+0.000043	test-rmse:0.163373+0.000230
[22]	train-rmse:0.155964+0.000049	test-rmse:0.156495+0.000235
[23]	train-rmse:0.149434+0.000049	test-rmse:0.150012+0.000248
[24]	train-rmse:0.143298+0.000060	test-rmse:0.143912+0.000255
[25]	train-rmse:0.137500+0.000066	test-rmse:0.138156+0.000263
[26]	train-rmse:0.132051+0.000077	test-rmse:0.132747+0.000271
[27]	train-rmse:0.126921+0.000075	test-rmse:0.127671+0.000292
[28]	train-rmse:0.122098+0.000079	test-rmse:0.122910+0.000303
[29]	train-rmse:0.117569+0.000079	test-rmse:0.118435+0.000325
[30]	train-rmse:0.113322+0.000079	test-rmse:0.114245+0.000341
[31]	train-rmse:0.109346+0.000095	test-rmse:0.110318+0.000354
[32]	train-rmse:0.105609+0.000100	test-rmse:0.106636+0.000365
[33]	train-rmse:0.102122+0.000107	test-rmse:0.103207+0.000378
[34]	train-rmse:0.098858+0.000111	test-rmse:0.100004+0.000394
[35]	train-rmse:0.095812+0.000112	test-rmse:0.097016+0.000412
[36]	train-rmse:0.092974+0.000116	test-rmse:0.094234+0.000437
[37]	train-rmse:0.090324+0.000120	test-rmse:0.091645+0.000452
[38]	train-rmse:0.087862+0.000123	test-rmse:0.089239+0.000469
[39]	train-rmse:0.085569+0.000134	test-rmse:0.087007+0.000486
[40]	train-rmse:0.083430+0.000136	test-rmse:0.084928+0.000501
[41]	train-rmse:0.081447+0.000141	test-rmse:0.083003+0.000518
[42]	train-rmse:0.079618+0.000146	test-rmse:0.081233+0.000531
[43]	train-rmse:0.077920+0.000150	test-rmse:0.079593+0.000549
[44]	train-rmse:0.076342+0.000149	test-rmse:0.078071+0.000568
[45]	train-rmse:0.074884+0.000151	test-rmse:0.076670+0.000582
[46]	train-rmse:0.073534+0.000157	test-rmse:0.075376+0.000592
[47]	train-rmse:0.072292+0.000155	test-rmse:0.074191+0.000611
[48]	train-rmse:0.071141+0.000157	test-rmse:0.073089+0.000628
[49]	train-rmse:0.070079+0.000157	test-rmse:0.072079+0.000642
[50]	train-rmse:0.069102+0.000169	test-rmse:0.071152+0.000652
[51]	train-rmse:0.068204+0.000167	test-rmse:0.070298+0.000666
[52]	train-rmse:0.067374+0.000171	test-rmse:0.069513+0.000678
[53]	train-rmse:0.066604+0.000170	test-rmse:0.068785+0.000696
[54]	train-rmse:0.065903+0.000172	test-rmse:0.068123+0.000706
[55]	train-rmse:0.065249+0.000169	test-rmse:0.067517+0.000721
[56]	train-rmse:0.064643+0.000172	test-rmse:0.066952+0.000730
[57]	train-rmse:0.064092+0.000178	test-rmse:0.066440+0.000741
[58]	train-rmse:0.063583+0.000180	test-rmse:0.065967+0.000749
[59]	train-rmse:0.063113+0.000183	test-rmse:0.065532+0.000762
[60]	train-rmse:0.062688+0.000188	test-rmse:0.065139+0.000768
[61]	train-rmse:0.062292+0.000190	test-rmse:0.064779+0.000774
[62]	train-rmse:0.061922+0.000189	test-rmse:0.064442+0.000782
[63]	train-rmse:0.061583+0.000189	test-rmse:0.064135+0.000787
[64]	train-rmse:0.061263+0.000180	test-rmse:0.063856+0.000791
[65]	train-rmse:0.060977+0.000183	test-rmse:0.063597+0.000797
[66]	train-rmse:0.060700+0.000182	test-rmse:0.063354+0.000806
[67]	train-rmse:0.060445+0.000181	test-rmse:0.063134+0.000808
[68]	train-rmse:0.060210+0.000186	test-rmse:0.062926+0.000803
[69]	train-rmse:0.059996+0.000186	test-rmse:0.062739+0.000810
[70]	train-rmse:0.059794+0.000179	test-rmse:0.062563+0.000821
[71]	train-rmse:0.059603+0.000178	test-rmse:0.062405+0.000824
[72]	train-rmse:0.059433+0.000175	test-rmse:0.062260+0.000831
[73]	train-rmse:0.059269+0.000177	test-rmse:0.062119+0.000834
[74]	train-rmse:0.059111+0.000180	test-rmse:0.061976+0.000835
[75]	train-rmse:0.058964+0.000176	test-rmse:0.061858+0.000839
[76]	train-rmse:0.058828+0.000170	test-rmse:0.061745+0.000846
[77]	train-rmse:0.058701+0.000167	test-rmse:0.061639+0.000852
[78]	train-rmse:0.058581+0.000169	test-rmse:0.061539+0.000852
[79]	train-rmse:0.058467+0.000172	test-rmse:0.061450+0.000854
[80]	train-rmse:0.058361+0.000170	test-rmse:0.061367+0.000856
[81]	train-rmse:0.058259+0.000169	test-rmse:0.061288+0.000856
[82]	train-rmse:0.058163+0.000173	test-rmse:0.061213+0.000852
[83]	train-rmse:0.058063+0.000173	test-rmse:0.061137+0.000856
[84]	train-rmse:0.057976+0.000175	test-rmse:0.061072+0.000854
[85]	train-rmse:0.057888+0.000175	test-rmse:0.061002+0.000848
[86]	train-rmse:0.057817+0.000173	test-rmse:0.060945+0.000850
[87]	train-rmse:0.057748+0.000184	test-rmse:0.060887+0.000839
[88]	train-rmse:0.057668+0.000180	test-rmse:0.060829+0.000845
[89]	train-rmse:0.057597+0.000181	test-rmse:0.060779+0.000844
[90]	train-rmse:0.057524+0.000181	test-rmse:0.060729+0.000842
[91]	train-rmse:0.057459+0.000180	test-rmse:0.060681+0.000845
[92]	train-rmse:0.057397+0.000182	test-rmse:0.060635+0.000844
[93]	train-rmse:0.057332+0.000185	test-rmse:0.060589+0.000842
[94]	train-rmse:0.057275+0.000187	test-rmse:0.060546+0.000841
[95]	train-rmse:0.057212+0.000190	test-rmse:0.060505+0.000838
[96]	train-rmse:0.057157+0.000191	test-rmse:0.060467+0.000839
[97]	train-rmse:0.057101+0.000195	test-rmse:0.060424+0.000842
[98]	train-rmse:0.057045+0.000199	test-rmse:0.060383+0.000839
[99]	train-rmse:0.056995+0.000199	test-rmse:0.060350+0.000842
[100]	train-rmse:0.056943+0.000204	test-rmse:0.060313+0.000838
[101]	train-rmse:0.056895+0.000204	test-rmse:0.060282+0.000839
[102]	train-rmse:0.056847+0.000204	test-rmse:0.060251+0.000839
[103]	train-rmse:0.056798+0.000204	test-rmse:0.060214+0.000838
[104]	train-rmse:0.056747+0.000201	test-rmse:0.060180+0.000840
[105]	train-rmse:0.056694+0.000195	test-rmse:0.060145+0.000841
[106]	train-rmse:0.056645+0.000196	test-rmse:0.060114+0.000838
[107]	train-rmse:0.056595+0.000201	test-rmse:0.060082+0.000839
[108]	train-rmse:0.056552+0.000198	test-rmse:0.060057+0.000841
[109]	train-rmse:0.056507+0.000202	test-rmse:0.060027+0.000840
[110]	train-rmse:0.056466+0.000203	test-rmse:0.059998+0.000842
[111]	train-rmse:0.056426+0.000204	test-rmse:0.059972+0.000843
[112]	train-rmse:0.056384+0.000199	test-rmse:0.059947+0.000846
[113]	train-rmse:0.056342+0.000191	test-rmse:0.059918+0.000852
[114]	train-rmse:0.056301+0.000192	test-rmse:0.059891+0.000851
[115]	train-rmse:0.056254+0.000191	test-rmse:0.059865+0.000852
[116]	train-rmse:0.056212+0.000191	test-rmse:0.059840+0.000850
[117]	train-rmse:0.056171+0.000189	test-rmse:0.059816+0.000850
[118]	train-rmse:0.056132+0.000187	test-rmse:0.059796+0.000854
[119]	train-rmse:0.056097+0.000186	test-rmse:0.059774+0.000855
[120]	train-rmse:0.056058+0.000185	test-rmse:0.059752+0.000854
[121]	train-rmse:0.056019+0.000183	test-rmse:0.059729+0.000855
[122]	train-rmse:0.055984+0.000184	test-rmse:0.059708+0.000853
[123]	train-rmse:0.055942+0.000189	test-rmse:0.059686+0.000853
[124]	train-rmse:0.055901+0.000189	test-rmse:0.059665+0.000850
[125]	train-rmse:0.055868+0.000186	test-rmse:0.059647+0.000852
[126]	train-rmse:0.055831+0.000187	test-rmse:0.059623+0.000849
[127]	train-rmse:0.055796+0.000188	test-rmse:0.059607+0.000852
[128]	train-rmse:0.055764+0.000188	test-rmse:0.059588+0.000850
[129]	train-rmse:0.055723+0.000185	test-rmse:0.059565+0.000854
[130]	train-rmse:0.055692+0.000187	test-rmse:0.059545+0.000853
[131]	train-rmse:0.055653+0.000196	test-rmse:0.059520+0.000849
[132]	train-rmse:0.055616+0.000198	test-rmse:0.059502+0.000851
[133]	train-rmse:0.055582+0.000200	test-rmse:0.059488+0.000852
[134]	train-rmse:0.055547+0.000200	test-rmse:0.059468+0.000854
[135]	train-rmse:0.055511+0.000200	test-rmse:0.059448+0.000852
[136]	train-rmse:0.055481+0.000200	test-rmse:0.059431+0.000849
[137]	train-rmse:0.055450+0.000198	test-rmse:0.059412+0.000850
[138]	train-rmse:0.055417+0.000199	test-rmse:0.059395+0.000848
[139]	train-rmse:0.055381+0.000200	test-rmse:0.059378+0.000846
[140]	train-rmse:0.055353+0.000201	test-rmse:0.059362+0.000844
[141]	train-rmse:0.055322+0.000204	test-rmse:0.059344+0.000843
[142]	train-rmse:0.055293+0.000206	test-rmse:0.059328+0.000842
[143]	train-rmse:0.055266+0.000213	test-rmse:0.059313+0.000837
[144]	train-rmse:0.055238+0.000213	test-rmse:0.059296+0.000840
[145]	train-rmse:0.055208+0.000212	test-rmse:0.059280+0.000841
[146]	train-rmse:0.055178+0.000209	test-rmse:0.059262+0.000843
[147]	train-rmse:0.055149+0.000209	test-rmse:0.059248+0.000845
[148]	train-rmse:0.055120+0.000210	test-rmse:0.059230+0.000843
[149]	train-rmse:0.055090+0.000212	test-rmse:0.059213+0.000841
[150]	train-rmse:0.055060+0.000210	test-rmse:0.059200+0.000840
[151]	train-rmse:0.055034+0.000212	test-rmse:0.059184+0.000839
[152]	train-rmse:0.055007+0.000213	test-rmse:0.059168+0.000837
[153]	train-rmse:0.054981+0.000212	test-rmse:0.059153+0.000841
[154]	train-rmse:0.054950+0.000214	test-rmse:0.059141+0.000841
[155]	train-rmse:0.054923+0.000215	test-rmse:0.059125+0.000843
[156]	train-rmse:0.054896+0.000219	test-rmse:0.059111+0.000842
[157]	train-rmse:0.054867+0.000219	test-rmse:0.059095+0.000842
[158]	train-rmse:0.054842+0.000221	test-rmse:0.059081+0.000842
[159]	train-rmse:0.054811+0.000225	test-rmse:0.059070+0.000843
[160]	train-rmse:0.054783+0.000225	test-rmse:0.059055+0.000847
[161]	train-rmse:0.054752+0.000227	test-rmse:0.059037+0.000843
[162]	train-rmse:0.054723+0.000221	test-rmse:0.059022+0.000844
[163]	train-rmse:0.054694+0.000220	test-rmse:0.059009+0.000845
[164]	train-rmse:0.054671+0.000217	test-rmse:0.058998+0.000845
[165]	train-rmse:0.054649+0.000220	test-rmse:0.058985+0.000845
[166]	train-rmse:0.054619+0.000223	test-rmse:0.058968+0.000844
[167]	train-rmse:0.054593+0.000224	test-rmse:0.058954+0.000847
[168]	train-rmse:0.054569+0.000225	test-rmse:0.058940+0.000846
[169]	train-rmse:0.054541+0.000223	test-rmse:0.058928+0.000846
[170]	train-rmse:0.054512+0.000223	test-rmse:0.058914+0.000841
[171]	train-rmse:0.054491+0.000222	test-rmse:0.058902+0.000841
[172]	train-rmse:0.054464+0.000219	test-rmse:0.058887+0.000841
[173]	train-rmse:0.054436+0.000217	test-rmse:0.058878+0.000840
[174]	train-rmse:0.054411+0.000217	test-rmse:0.058863+0.000841
[175]	train-rmse:0.054388+0.000216	test-rmse:0.058848+0.000842
[176]	train-rmse:0.054367+0.000214	test-rmse:0.058839+0.000841
[177]	train-rmse:0.054344+0.000212	test-rmse:0.058825+0.000845
[178]	train-rmse:0.054318+0.000212	test-rmse:0.058815+0.000846
[179]	train-rmse:0.054293+0.000211	test-rmse:0.058805+0.000844
[180]	train-rmse:0.054272+0.000213	test-rmse:0.058794+0.000842
[181]	train-rmse:0.054248+0.000213	test-rmse:0.058782+0.000839
[182]	train-rmse:0.054229+0.000210	test-rmse:0.058775+0.000840
[183]	train-rmse:0.054210+0.000203	test-rmse:0.058767+0.000842
[184]	train-rmse:0.054186+0.000205	test-rmse:0.058755+0.000845
[185]	train-rmse:0.054159+0.000204	test-rmse:0.058744+0.000842
[186]	train-rmse:0.054138+0.000203	test-rmse:0.058733+0.000843
[187]	train-rmse:0.054114+0.000203	test-rmse:0.058721+0.000843
[188]	train-rmse:0.054094+0.000203	test-rmse:0.058712+0.000841
[189]	train-rmse:0.054074+0.000203	test-rmse:0.058702+0.000842
[190]	train-rmse:0.054049+0.000199	test-rmse:0.058689+0.000843
[191]	train-rmse:0.054029+0.000198	test-rmse:0.058679+0.000845
[192]	train-rmse:0.054009+0.000197	test-rmse:0.058670+0.000845
[193]	train-rmse:0.053990+0.000196	test-rmse:0.058663+0.000848
[194]	train-rmse:0.053969+0.000198	test-rmse:0.058652+0.000848
[195]	train-rmse:0.053945+0.000195	test-rmse:0.058643+0.000848
[196]	train-rmse:0.053924+0.000193	test-rmse:0.058631+0.000850
[197]	train-rmse:0.053903+0.000192	test-rmse:0.058621+0.000851
[198]	train-rmse:0.053880+0.000193	test-rmse:0.058611+0.000850
[199]	train-rmse:0.053858+0.000197	test-rmse:0.058600+0.000849
[200]	train-rmse:0.053837+0.000201	test-rmse:0.058589+0.000849
[201]	train-rmse:0.053818+0.000204	test-rmse:0.058582+0.000851
[202]	train-rmse:0.053799+0.000203	test-rmse:0.058570+0.000850
[203]	train-rmse:0.053778+0.000201	test-rmse:0.058562+0.000848
[204]	train-rmse:0.053757+0.000201	test-rmse:0.058553+0.000852
[205]	train-rmse:0.053738+0.000202	test-rmse:0.058542+0.000852
[206]	train-rmse:0.053721+0.000200	test-rmse:0.058538+0.000851
[207]	train-rmse:0.053700+0.000197	test-rmse:0.058530+0.000848
[208]	train-rmse:0.053682+0.000199	test-rmse:0.058520+0.000846
[209]	train-rmse:0.053661+0.000193	test-rmse:0.058509+0.000852
[210]	train-rmse:0.053644+0.000193	test-rmse:0.058499+0.000852
[211]	train-rmse:0.053625+0.000196	test-rmse:0.058490+0.000849
[212]	train-rmse:0.053604+0.000191	test-rmse:0.058480+0.000850
[213]	train-rmse:0.053588+0.000191	test-rmse:0.058472+0.000850
[214]	train-rmse:0.053566+0.000191	test-rmse:0.058461+0.000851
[215]	train-rmse:0.053545+0.000189	test-rmse:0.058451+0.000849
[216]	train-rmse:0.053524+0.000188	test-rmse:0.058442+0.000849
[217]	train-rmse:0.053504+0.000187	test-rmse:0.058435+0.000848
[218]	train-rmse:0.053487+0.000188	test-rmse:0.058429+0.000848
[219]	train-rmse:0.053466+0.000186	test-rmse:0.058417+0.000846
[220]	train-rmse:0.053446+0.000186	test-rmse:0.058409+0.000846
[221]	train-rmse:0.053428+0.000189	test-rmse:0.058403+0.000847
[222]	train-rmse:0.053409+0.000186	test-rmse:0.058395+0.000847
[223]	train-rmse:0.053389+0.000186	test-rmse:0.058385+0.000846
[224]	train-rmse:0.053370+0.000188	test-rmse:0.058377+0.000846
[225]	train-rmse:0.053355+0.000188	test-rmse:0.058370+0.000847
[226]	train-rmse:0.053339+0.000187	test-rmse:0.058364+0.000847
[227]	train-rmse:0.053324+0.000189	test-rmse:0.058358+0.000846
[228]	train-rmse:0.053307+0.000194	test-rmse:0.058349+0.000842
[229]	train-rmse:0.053296+0.000196	test-rmse:0.058344+0.000839
[230]	train-rmse:0.053279+0.000196	test-rmse:0.058334+0.000837
[231]	train-rmse:0.053262+0.000192	test-rmse:0.058327+0.000837
[232]	train-rmse:0.053246+0.000192	test-rmse:0.058320+0.000834
[233]	train-rmse:0.053230+0.000193	test-rmse:0.058314+0.000835
[234]	train-rmse:0.053210+0.000193	test-rmse:0.058306+0.000833
[235]	train-rmse:0.053194+0.000195	test-rmse:0.058299+0.000833
[236]	train-rmse:0.053177+0.000195	test-rmse:0.058294+0.000833
[237]	train-rmse:0.053161+0.000198	test-rmse:0.058288+0.000832
[238]	train-rmse:0.053147+0.000201	test-rmse:0.058281+0.000836
[239]	train-rmse:0.053135+0.000202	test-rmse:0.058275+0.000837
[240]	train-rmse:0.053119+0.000202	test-rmse:0.058268+0.000838
[241]	train-rmse:0.053104+0.000204	test-rmse:0.058265+0.000838
[242]	train-rmse:0.053086+0.000205	test-rmse:0.058257+0.000838
[243]	train-rmse:0.053066+0.000206	test-rmse:0.058248+0.000836
[244]	train-rmse:0.053046+0.000206	test-rmse:0.058242+0.000835
[245]	train-rmse:0.053029+0.000205	test-rmse:0.058237+0.000836
[246]	train-rmse:0.053014+0.000205	test-rmse:0.058229+0.000834
[247]	train-rmse:0.052998+0.000204	test-rmse:0.058223+0.000834
[248]	train-rmse:0.052984+0.000206	test-rmse:0.058217+0.000833
[249]	train-rmse:0.052969+0.000206	test-rmse:0.058211+0.000833
[250]	train-rmse:0.052954+0.000209	test-rmse:0.058205+0.000833
[251]	train-rmse:0.052937+0.000211	test-rmse:0.058196+0.000830
[252]	train-rmse:0.052920+0.000208	test-rmse:0.058188+0.000831
[253]	train-rmse:0.052902+0.000207	test-rmse:0.058182+0.000829
[254]	train-rmse:0.052886+0.000206	test-rmse:0.058177+0.000830
[255]	train-rmse:0.052872+0.000208	test-rmse:0.058172+0.000831
[256]	train-rmse:0.052857+0.000206	test-rmse:0.058164+0.000831
[257]	train-rmse:0.052841+0.000205	test-rmse:0.058157+0.000830
[258]	train-rmse:0.052822+0.000200	test-rmse:0.058149+0.000831
[259]	train-rmse:0.052809+0.000201	test-rmse:0.058144+0.000831
[260]	train-rmse:0.052792+0.000199	test-rmse:0.058137+0.000829
[261]	train-rmse:0.052775+0.000196	test-rmse:0.058130+0.000828
[262]	train-rmse:0.052761+0.000200	test-rmse:0.058123+0.000829
[263]	train-rmse:0.052750+0.000200	test-rmse:0.058120+0.000827
[264]	train-rmse:0.052738+0.000199	test-rmse:0.058115+0.000829
[265]	train-rmse:0.052721+0.000200	test-rmse:0.058108+0.000828
[266]	train-rmse:0.052706+0.000200	test-rmse:0.058100+0.000825
[267]	train-rmse:0.052690+0.000198	test-rmse:0.058093+0.000825
[268]	train-rmse:0.052674+0.000200	test-rmse:0.058088+0.000825
[269]	train-rmse:0.052659+0.000201	test-rmse:0.058082+0.000825
[270]	train-rmse:0.052646+0.000202	test-rmse:0.058077+0.000823
[271]	train-rmse:0.052630+0.000203	test-rmse:0.058072+0.000824
[272]	train-rmse:0.052614+0.000207	test-rmse:0.058067+0.000825
[273]	train-rmse:0.052598+0.000210	test-rmse:0.058061+0.000827
[274]	train-rmse:0.052581+0.000211	test-rmse:0.058054+0.000827
[275]	train-rmse:0.052566+0.000212	test-rmse:0.058048+0.000828
[276]	train-rmse:0.052553+0.000216	test-rmse:0.058046+0.000831
[277]	train-rmse:0.052536+0.000216	test-rmse:0.058035+0.000830
[278]	train-rmse:0.052522+0.000217	test-rmse:0.058031+0.000829
[279]	train-rmse:0.052509+0.000217	test-rmse:0.058026+0.000829
[280]	train-rmse:0.052496+0.000218	test-rmse:0.058020+0.000830
[281]	train-rmse:0.052481+0.000217	test-rmse:0.058013+0.000831
[282]	train-rmse:0.052464+0.000214	test-rmse:0.058007+0.000831
[283]	train-rmse:0.052446+0.000209	test-rmse:0.058000+0.000831
[284]	train-rmse:0.052428+0.000207	test-rmse:0.057994+0.000828
[285]	train-rmse:0.052411+0.000208	test-rmse:0.057987+0.000827
[286]	train-rmse:0.052396+0.000206	test-rmse:0.057983+0.000828
[287]	train-rmse:0.052377+0.000206	test-rmse:0.057976+0.000827
[288]	train-rmse:0.052370+0.000209	test-rmse:0.057972+0.000827
[289]	train-rmse:0.052356+0.000208	test-rmse:0.057967+0.000827
[290]	train-rmse:0.052340+0.000212	test-rmse:0.057962+0.000826
[291]	train-rmse:0.052329+0.000212	test-rmse:0.057958+0.000826
[292]	train-rmse:0.052314+0.000214	test-rmse:0.057947+0.000821
[293]	train-rmse:0.052301+0.000212	test-rmse:0.057942+0.000823
[294]	train-rmse:0.052288+0.000211	test-rmse:0.057937+0.000825
[295]	train-rmse:0.052277+0.000212	test-rmse:0.057933+0.000826
[296]	train-rmse:0.052263+0.000213	test-rmse:0.057925+0.000826
[297]	train-rmse:0.052252+0.000217	test-rmse:0.057920+0.000823
[298]	train-rmse:0.052239+0.000218	test-rmse:0.057915+0.000823
[299]	train-rmse:0.052224+0.000218	test-rmse:0.057908+0.000821
[300]	train-rmse:0.052211+0.000218	test-rmse:0.057903+0.000820
[301]	train-rmse:0.052196+0.000215	test-rmse:0.057896+0.000821
[302]	train-rmse:0.052181+0.000216	test-rmse:0.057890+0.000822
[303]	train-rmse:0.052170+0.000216	test-rmse:0.057887+0.000820
[304]	train-rmse:0.052158+0.000215	test-rmse:0.057882+0.000820
[305]	train-rmse:0.052146+0.000217	test-rmse:0.057877+0.000817
[306]	train-rmse:0.052133+0.000218	test-rmse:0.057873+0.000817
[307]	train-rmse:0.052118+0.000219	test-rmse:0.057868+0.000816
[308]	train-rmse:0.052102+0.000220	test-rmse:0.057862+0.000815
[309]	train-rmse:0.052092+0.000224	test-rmse:0.057860+0.000816
[310]	train-rmse:0.052080+0.000224	test-rmse:0.057857+0.000813
[311]	train-rmse:0.052067+0.000224	test-rmse:0.057854+0.000812
[312]	train-rmse:0.052056+0.000225	test-rmse:0.057850+0.000810
[313]	train-rmse:0.052046+0.000221	test-rmse:0.057845+0.000810
[314]	train-rmse:0.052034+0.000222	test-rmse:0.057842+0.000810
[315]	train-rmse:0.052022+0.000225	test-rmse:0.057839+0.000811
[316]	train-rmse:0.052009+0.000226	test-rmse:0.057834+0.000809
[317]	train-rmse:0.051998+0.000227	test-rmse:0.057829+0.000808

In [14]:
param = list(
    objective        = "reg:squarederror",
    eval_metric      = "rmse",
    max_depth        = 6,
    eta              = 0.1,
    subsample        = 0.8,
    colsample_bytree = 0.8,
    nthread          = 8
)

### start timer
time_start = Sys.time()

### init seed
set.seed(123)

fit_xgb_cv = xgboost::xgb.cv(
    params = param,
    data   = dtrain,
    nrounds = 1000,
    nfold   = 5,
    early_stopping_rounds = 50,
    verbose = 1
)

### assign and show
best_iter = fit_xgb_cv$best_iteration
print(best_iter)
print(fit_xgb_cv$best_score)

### end timer
time_end = Sys.time()

### print elapsed time
print(time_end - time_start)

[1]	train-rmse:0.401393+0.000046	test-rmse:0.401417+0.000214
Multiple eval metrics are present. Will use test_rmse for early stopping.
Will train until test_rmse hasn't improved in 50 rounds.

[2]	train-rmse:0.362382+0.000034	test-rmse:0.362432+0.000213
[3]	train-rmse:0.327397+0.000032	test-rmse:0.327482+0.000199
[4]	train-rmse:0.296018+0.000028	test-rmse:0.296140+0.000214
[5]	train-rmse:0.267904+0.000020	test-rmse:0.268071+0.000206
[6]	train-rmse:0.242722+0.000012	test-rmse:0.242936+0.000207
[7]	train-rmse:0.220203+0.000013	test-rmse:0.220478+0.000211
[8]	train-rmse:0.200090+0.000031	test-rmse:0.200428+0.000219
[9]	train-rmse:0.182175+0.000043	test-rmse:0.182581+0.000236
[10]	train-rmse:0.166215+0.000047	test-rmse:0.166705+0.000246
[11]	train-rmse:0.152053+0.000058	test-rmse:0.152615+0.000267
[12]	train-rmse:0.139501+0.000075	test-rmse:0.140153+0.000279
[13]	train-rmse:0.128429+0.000069	test-rmse:0.129175+0.000307
[14]	train-rmse:0.118663+0.000082	test-rmse:0.119513+0.000330
[15]	train-rmse:0.110104+0.000096	test-rmse:0.111074+0.000354
[16]	train-rmse:0.102615+0.000127	test-rmse:0.103697+0.000384
[17]	train-rmse:0.096098+0.000134	test-rmse:0.097299+0.000423
[18]	train-rmse:0.090440+0.000146	test-rmse:0.091768+0.000458
[19]	train-rmse:0.085562+0.000147	test-rmse:0.087007+0.000494
[20]	train-rmse:0.081359+0.000158	test-rmse:0.082933+0.000534
[21]	train-rmse:0.077774+0.000162	test-rmse:0.079464+0.000572
[22]	train-rmse:0.074706+0.000168	test-rmse:0.076506+0.000592
[23]	train-rmse:0.072108+0.000185	test-rmse:0.074012+0.000621
[24]	train-rmse:0.069898+0.000176	test-rmse:0.071904+0.000653
[25]	train-rmse:0.068027+0.000187	test-rmse:0.070126+0.000673
[26]	train-rmse:0.066448+0.000198	test-rmse:0.068643+0.000695
[27]	train-rmse:0.065121+0.000196	test-rmse:0.067390+0.000732
[28]	train-rmse:0.063989+0.000193	test-rmse:0.066331+0.000748
[29]	train-rmse:0.063032+0.000198	test-rmse:0.065449+0.000763
[30]	train-rmse:0.062224+0.000201	test-rmse:0.064713+0.000789
[31]	train-rmse:0.061528+0.000217	test-rmse:0.064080+0.000804
[32]	train-rmse:0.060944+0.000212	test-rmse:0.063560+0.000820
[33]	train-rmse:0.060442+0.000214	test-rmse:0.063116+0.000837
[34]	train-rmse:0.060013+0.000224	test-rmse:0.062740+0.000850
[35]	train-rmse:0.059640+0.000227	test-rmse:0.062412+0.000867
[36]	train-rmse:0.059299+0.000223	test-rmse:0.062127+0.000867
[37]	train-rmse:0.059013+0.000213	test-rmse:0.061890+0.000881
[38]	train-rmse:0.058754+0.000212	test-rmse:0.061683+0.000892
[39]	train-rmse:0.058525+0.000205	test-rmse:0.061503+0.000895
[40]	train-rmse:0.058318+0.000204	test-rmse:0.061340+0.000903
[41]	train-rmse:0.058140+0.000203	test-rmse:0.061205+0.000918
[42]	train-rmse:0.057979+0.000214	test-rmse:0.061084+0.000918
[43]	train-rmse:0.057826+0.000209	test-rmse:0.060975+0.000916
[44]	train-rmse:0.057673+0.000212	test-rmse:0.060871+0.000918
[45]	train-rmse:0.057538+0.000220	test-rmse:0.060773+0.000906
[46]	train-rmse:0.057416+0.000228	test-rmse:0.060679+0.000893
[47]	train-rmse:0.057304+0.000221	test-rmse:0.060613+0.000894
[48]	train-rmse:0.057188+0.000228	test-rmse:0.060537+0.000898
[49]	train-rmse:0.057084+0.000231	test-rmse:0.060463+0.000890
[50]	train-rmse:0.056985+0.000226	test-rmse:0.060400+0.000886
[51]	train-rmse:0.056893+0.000222	test-rmse:0.060341+0.000888
[52]	train-rmse:0.056809+0.000220	test-rmse:0.060276+0.000897
[53]	train-rmse:0.056715+0.000211	test-rmse:0.060210+0.000896
[54]	train-rmse:0.056627+0.000205	test-rmse:0.060159+0.000889
[55]	train-rmse:0.056535+0.000208	test-rmse:0.060100+0.000885
[56]	train-rmse:0.056456+0.000213	test-rmse:0.060038+0.000879
[57]	train-rmse:0.056380+0.000214	test-rmse:0.059987+0.000877
[58]	train-rmse:0.056295+0.000215	test-rmse:0.059934+0.000888
[59]	train-rmse:0.056224+0.000210	test-rmse:0.059896+0.000894
[60]	train-rmse:0.056153+0.000216	test-rmse:0.059850+0.000897
[61]	train-rmse:0.056083+0.000219	test-rmse:0.059802+0.000890
[62]	train-rmse:0.056010+0.000217	test-rmse:0.059760+0.000883
[63]	train-rmse:0.055939+0.000219	test-rmse:0.059716+0.000879
[64]	train-rmse:0.055875+0.000224	test-rmse:0.059676+0.000875
[65]	train-rmse:0.055804+0.000219	test-rmse:0.059638+0.000873
[66]	train-rmse:0.055731+0.000215	test-rmse:0.059596+0.000866
[67]	train-rmse:0.055667+0.000223	test-rmse:0.059561+0.000859
[68]	train-rmse:0.055604+0.000217	test-rmse:0.059526+0.000867
[69]	train-rmse:0.055547+0.000219	test-rmse:0.059495+0.000873
[70]	train-rmse:0.055488+0.000218	test-rmse:0.059461+0.000876
[71]	train-rmse:0.055426+0.000227	test-rmse:0.059432+0.000871
[72]	train-rmse:0.055361+0.000212	test-rmse:0.059404+0.000873
[73]	train-rmse:0.055305+0.000206	test-rmse:0.059374+0.000874
[74]	train-rmse:0.055254+0.000203	test-rmse:0.059344+0.000876
[75]	train-rmse:0.055197+0.000203	test-rmse:0.059313+0.000871
[76]	train-rmse:0.055136+0.000209	test-rmse:0.059281+0.000871
[77]	train-rmse:0.055090+0.000209	test-rmse:0.059255+0.000871
[78]	train-rmse:0.055030+0.000205	test-rmse:0.059224+0.000875
[79]	train-rmse:0.054976+0.000198	test-rmse:0.059199+0.000876
[80]	train-rmse:0.054926+0.000202	test-rmse:0.059176+0.000872
[81]	train-rmse:0.054875+0.000201	test-rmse:0.059149+0.000868
[82]	train-rmse:0.054822+0.000199	test-rmse:0.059116+0.000864
[83]	train-rmse:0.054772+0.000191	test-rmse:0.059095+0.000871
[84]	train-rmse:0.054721+0.000194	test-rmse:0.059070+0.000866
[85]	train-rmse:0.054671+0.000195	test-rmse:0.059050+0.000867
[86]	train-rmse:0.054633+0.000186	test-rmse:0.059030+0.000873
[87]	train-rmse:0.054585+0.000194	test-rmse:0.059008+0.000871
[88]	train-rmse:0.054526+0.000192	test-rmse:0.058981+0.000870
[89]	train-rmse:0.054478+0.000186	test-rmse:0.058959+0.000871
[90]	train-rmse:0.054437+0.000193	test-rmse:0.058939+0.000866
[91]	train-rmse:0.054394+0.000191	test-rmse:0.058918+0.000869
[92]	train-rmse:0.054351+0.000193	test-rmse:0.058896+0.000868
[93]	train-rmse:0.054307+0.000189	test-rmse:0.058877+0.000870
[94]	train-rmse:0.054267+0.000188	test-rmse:0.058857+0.000869
[95]	train-rmse:0.054217+0.000186	test-rmse:0.058839+0.000867
[96]	train-rmse:0.054175+0.000184	test-rmse:0.058822+0.000865
[97]	train-rmse:0.054133+0.000183	test-rmse:0.058801+0.000869
[98]	train-rmse:0.054090+0.000190	test-rmse:0.058776+0.000862
[99]	train-rmse:0.054046+0.000192	test-rmse:0.058757+0.000864
[100]	train-rmse:0.054013+0.000189	test-rmse:0.058743+0.000869
[101]	train-rmse:0.053976+0.000183	test-rmse:0.058724+0.000869
[102]	train-rmse:0.053930+0.000183	test-rmse:0.058706+0.000871
[103]	train-rmse:0.053886+0.000182	test-rmse:0.058687+0.000868
[104]	train-rmse:0.053851+0.000185	test-rmse:0.058674+0.000865
[105]	train-rmse:0.053817+0.000190	test-rmse:0.058656+0.000859
[106]	train-rmse:0.053782+0.000189	test-rmse:0.058640+0.000854
[107]	train-rmse:0.053749+0.000188	test-rmse:0.058628+0.000852
[108]	train-rmse:0.053704+0.000185	test-rmse:0.058609+0.000853
[109]	train-rmse:0.053660+0.000186	test-rmse:0.058579+0.000851
[110]	train-rmse:0.053622+0.000190	test-rmse:0.058565+0.000848
[111]	train-rmse:0.053600+0.000191	test-rmse:0.058554+0.000852
[112]	train-rmse:0.053567+0.000194	test-rmse:0.058541+0.000852
[113]	train-rmse:0.053535+0.000191	test-rmse:0.058522+0.000848
[114]	train-rmse:0.053491+0.000197	test-rmse:0.058500+0.000851
[115]	train-rmse:0.053454+0.000200	test-rmse:0.058486+0.000856
[116]	train-rmse:0.053422+0.000199	test-rmse:0.058472+0.000857
[117]	train-rmse:0.053386+0.000202	test-rmse:0.058459+0.000854
[118]	train-rmse:0.053356+0.000207	test-rmse:0.058446+0.000855
[119]	train-rmse:0.053323+0.000204	test-rmse:0.058432+0.000860
[120]	train-rmse:0.053296+0.000200	test-rmse:0.058421+0.000862
[121]	train-rmse:0.053272+0.000191	test-rmse:0.058413+0.000863
[122]	train-rmse:0.053243+0.000196	test-rmse:0.058402+0.000864
[123]	train-rmse:0.053208+0.000195	test-rmse:0.058388+0.000860
[124]	train-rmse:0.053175+0.000199	test-rmse:0.058374+0.000863
[125]	train-rmse:0.053149+0.000187	test-rmse:0.058365+0.000862
[126]	train-rmse:0.053118+0.000198	test-rmse:0.058348+0.000856
[127]	train-rmse:0.053096+0.000201	test-rmse:0.058338+0.000859
[128]	train-rmse:0.053066+0.000200	test-rmse:0.058326+0.000861
[129]	train-rmse:0.053031+0.000201	test-rmse:0.058316+0.000859
[130]	train-rmse:0.053006+0.000206	test-rmse:0.058305+0.000857
[131]	train-rmse:0.052972+0.000206	test-rmse:0.058296+0.000856
[132]	train-rmse:0.052952+0.000202	test-rmse:0.058289+0.000860
[133]	train-rmse:0.052930+0.000205	test-rmse:0.058283+0.000861
[134]	train-rmse:0.052907+0.000191	test-rmse:0.058274+0.000864
[135]	train-rmse:0.052881+0.000203	test-rmse:0.058261+0.000862
[136]	train-rmse:0.052852+0.000208	test-rmse:0.058248+0.000860
[137]	train-rmse:0.052828+0.000214	test-rmse:0.058241+0.000861
[138]	train-rmse:0.052806+0.000215	test-rmse:0.058230+0.000865
[139]	train-rmse:0.052781+0.000214	test-rmse:0.058222+0.000866
[140]	train-rmse:0.052754+0.000216	test-rmse:0.058214+0.000867
[141]	train-rmse:0.052735+0.000209	test-rmse:0.058205+0.000872
[142]	train-rmse:0.052704+0.000215	test-rmse:0.058191+0.000878
[143]	train-rmse:0.052678+0.000226	test-rmse:0.058178+0.000876
[144]	train-rmse:0.052658+0.000234	test-rmse:0.058171+0.000877
[145]	train-rmse:0.052641+0.000233	test-rmse:0.058162+0.000875
[146]	train-rmse:0.052609+0.000234	test-rmse:0.058154+0.000876
[147]	train-rmse:0.052582+0.000244	test-rmse:0.058148+0.000876
[148]	train-rmse:0.052545+0.000240	test-rmse:0.058139+0.000872
[149]	train-rmse:0.052516+0.000241	test-rmse:0.058127+0.000869
[150]	train-rmse:0.052487+0.000243	test-rmse:0.058119+0.000869
[151]	train-rmse:0.052459+0.000244	test-rmse:0.058112+0.000871
[152]	train-rmse:0.052433+0.000240	test-rmse:0.058105+0.000869
[153]	train-rmse:0.052408+0.000230	test-rmse:0.058099+0.000872
[154]	train-rmse:0.052382+0.000232	test-rmse:0.058095+0.000871
[155]	train-rmse:0.052363+0.000237	test-rmse:0.058090+0.000871
[156]	train-rmse:0.052351+0.000239	test-rmse:0.058085+0.000873
[157]	train-rmse:0.052326+0.000249	test-rmse:0.058078+0.000874
[158]	train-rmse:0.052310+0.000248	test-rmse:0.058070+0.000872
[159]	train-rmse:0.052282+0.000240	test-rmse:0.058065+0.000876
[160]	train-rmse:0.052262+0.000243	test-rmse:0.058055+0.000876
[161]	train-rmse:0.052237+0.000237	test-rmse:0.058044+0.000881
[162]	train-rmse:0.052201+0.000227	test-rmse:0.058030+0.000882
[163]	train-rmse:0.052185+0.000234	test-rmse:0.058028+0.000885
[164]	train-rmse:0.052164+0.000239	test-rmse:0.058018+0.000883
[165]	train-rmse:0.052145+0.000239	test-rmse:0.058012+0.000883
[166]	train-rmse:0.052119+0.000240	test-rmse:0.058000+0.000878
[167]	train-rmse:0.052098+0.000246	test-rmse:0.057993+0.000877
[168]	train-rmse:0.052079+0.000254	test-rmse:0.057988+0.000877
[169]	train-rmse:0.052046+0.000251	test-rmse:0.057979+0.000874
[170]	train-rmse:0.052022+0.000254	test-rmse:0.057976+0.000872
[171]	train-rmse:0.052003+0.000255	test-rmse:0.057971+0.000868
[172]	train-rmse:0.051979+0.000256	test-rmse:0.057959+0.000865
[173]	train-rmse:0.051955+0.000252	test-rmse:0.057950+0.000861
[174]	train-rmse:0.051928+0.000250	test-rmse:0.057942+0.000863
[175]	train-rmse:0.051908+0.000244	test-rmse:0.057932+0.000863
[176]	train-rmse:0.051888+0.000254	test-rmse:0.057924+0.000862
[177]	train-rmse:0.051865+0.000257	test-rmse:0.057913+0.000856
[178]	train-rmse:0.051843+0.000258	test-rmse:0.057907+0.000856
[179]	train-rmse:0.051820+0.000251	test-rmse:0.057902+0.000849
[180]	train-rmse:0.051792+0.000254	test-rmse:0.057896+0.000845
[181]	train-rmse:0.051771+0.000255	test-rmse:0.057889+0.000843
[182]	train-rmse:0.051750+0.000262	test-rmse:0.057883+0.000839
[183]	train-rmse:0.051736+0.000252	test-rmse:0.057878+0.000840
[184]	train-rmse:0.051709+0.000251	test-rmse:0.057868+0.000842
[185]	train-rmse:0.051688+0.000249	test-rmse:0.057863+0.000845
[186]	train-rmse:0.051675+0.000246	test-rmse:0.057858+0.000849
[187]	train-rmse:0.051658+0.000237	test-rmse:0.057853+0.000854
[188]	train-rmse:0.051636+0.000236	test-rmse:0.057848+0.000855
[189]	train-rmse:0.051618+0.000239	test-rmse:0.057843+0.000856
[190]	train-rmse:0.051596+0.000236	test-rmse:0.057836+0.000858
[191]	train-rmse:0.051577+0.000234	test-rmse:0.057827+0.000858
[192]	train-rmse:0.051556+0.000238	test-rmse:0.057820+0.000858
[193]	train-rmse:0.051544+0.000244	test-rmse:0.057816+0.000861
[194]	train-rmse:0.051521+0.000247	test-rmse:0.057809+0.000862
[195]	train-rmse:0.051507+0.000248	test-rmse:0.057806+0.000859
[196]	train-rmse:0.051498+0.000247	test-rmse:0.057802+0.000857
[197]	train-rmse:0.051477+0.000237	test-rmse:0.057796+0.000855
[198]	train-rmse:0.051455+0.000233	test-rmse:0.057789+0.000853
[199]	train-rmse:0.051443+0.000239	test-rmse:0.057783+0.000851
[200]	train-rmse:0.051420+0.000243	test-rmse:0.057775+0.000849
[201]	train-rmse:0.051403+0.000237	test-rmse:0.057771+0.000850
[202]	train-rmse:0.051377+0.000235	test-rmse:0.057762+0.000854
[203]	train-rmse:0.051360+0.000232	test-rmse:0.057754+0.000854
[204]	train-rmse:0.051342+0.000237	test-rmse:0.057751+0.000852
[205]	train-rmse:0.051322+0.000233	test-rmse:0.057748+0.000850
[206]	train-rmse:0.051303+0.000235	test-rmse:0.057742+0.000847
[207]	train-rmse:0.051287+0.000232	test-rmse:0.057739+0.000847
[208]	train-rmse:0.051264+0.000232	test-rmse:0.057731+0.000845
[209]	train-rmse:0.051247+0.000230	test-rmse:0.057722+0.000843
[210]	train-rmse:0.051239+0.000227	test-rmse:0.057719+0.000840
[211]	train-rmse:0.051217+0.000230	test-rmse:0.057710+0.000840
[212]	train-rmse:0.051205+0.000222	test-rmse:0.057706+0.000840
[213]	train-rmse:0.051197+0.000226	test-rmse:0.057704+0.000840
[214]	train-rmse:0.051178+0.000228	test-rmse:0.057695+0.000842
[215]	train-rmse:0.051175+0.000230	test-rmse:0.057695+0.000842
[216]	train-rmse:0.051156+0.000231	test-rmse:0.057687+0.000840
[217]	train-rmse:0.051141+0.000229	test-rmse:0.057683+0.000839
[218]	train-rmse:0.051136+0.000235	test-rmse:0.057681+0.000839
[219]	train-rmse:0.051114+0.000225	test-rmse:0.057674+0.000842
[220]	train-rmse:0.051092+0.000224	test-rmse:0.057667+0.000840
[221]	train-rmse:0.051079+0.000224	test-rmse:0.057664+0.000839
[222]	train-rmse:0.051069+0.000226	test-rmse:0.057662+0.000837
[223]	train-rmse:0.051052+0.000231	test-rmse:0.057658+0.000834
[224]	train-rmse:0.051029+0.000228	test-rmse:0.057652+0.000835
[225]	train-rmse:0.051023+0.000235	test-rmse:0.057651+0.000835
[226]	train-rmse:0.051005+0.000235	test-rmse:0.057644+0.000833
[227]	train-rmse:0.050987+0.000227	test-rmse:0.057643+0.000836
[228]	train-rmse:0.050968+0.000227	test-rmse:0.057637+0.000838
[229]	train-rmse:0.050951+0.000229	test-rmse:0.057632+0.000835
[230]	train-rmse:0.050938+0.000232	test-rmse:0.057626+0.000830
[231]	train-rmse:0.050935+0.000235	test-rmse:0.057625+0.000830
[232]	train-rmse:0.050920+0.000244	test-rmse:0.057620+0.000830
[233]	train-rmse:0.050905+0.000245	test-rmse:0.057615+0.000831
[234]	train-rmse:0.050886+0.000241	test-rmse:0.057609+0.000827
[235]	train-rmse:0.050867+0.000237	test-rmse:0.057602+0.000827
[236]	train-rmse:0.050850+0.000238	test-rmse:0.057598+0.000827
[237]	train-rmse:0.050833+0.000236	test-rmse:0.057594+0.000828
[238]	train-rmse:0.050822+0.000241	test-rmse:0.057591+0.000824
[239]	train-rmse:0.050805+0.000242	test-rmse:0.057584+0.000827
[240]	train-rmse:0.050795+0.000247	test-rmse:0.057581+0.000824
[241]	train-rmse:0.050784+0.000249	test-rmse:0.057580+0.000823
[242]	train-rmse:0.050766+0.000254	test-rmse:0.057573+0.000820
[243]	train-rmse:0.050758+0.000250	test-rmse:0.057570+0.000820
[244]	train-rmse:0.050750+0.000259	test-rmse:0.057568+0.000819
[245]	train-rmse:0.050738+0.000263	test-rmse:0.057564+0.000817
[246]	train-rmse:0.050715+0.000258	test-rmse:0.057557+0.000812
[247]	train-rmse:0.050710+0.000256	test-rmse:0.057556+0.000811
[248]	train-rmse:0.050698+0.000257	test-rmse:0.057551+0.000810
[249]	train-rmse:0.050689+0.000252	test-rmse:0.057550+0.000810
[250]	train-rmse:0.050681+0.000251	test-rmse:0.057549+0.000811
[251]	train-rmse:0.050662+0.000247	test-rmse:0.057543+0.000812
[252]	train-rmse:0.050647+0.000245	test-rmse:0.057542+0.000811
[253]	train-rmse:0.050629+0.000239	test-rmse:0.057538+0.000810
[254]	train-rmse:0.050619+0.000240	test-rmse:0.057534+0.000808
[255]	train-rmse:0.050595+0.000242	test-rmse:0.057529+0.000808
[256]	train-rmse:0.050574+0.000241	test-rmse:0.057519+0.000810
[257]	train-rmse:0.050568+0.000235	test-rmse:0.057517+0.000810
[258]	train-rmse:0.050556+0.000225	test-rmse:0.057513+0.000811
[259]	train-rmse:0.050541+0.000218	test-rmse:0.057509+0.000813
[260]	train-rmse:0.050522+0.000226	test-rmse:0.057505+0.000809
[261]	train-rmse:0.050510+0.000231	test-rmse:0.057504+0.000809
[262]	train-rmse:0.050492+0.000230	test-rmse:0.057499+0.000811
[263]	train-rmse:0.050475+0.000233	test-rmse:0.057493+0.000808
[264]	train-rmse:0.050469+0.000232	test-rmse:0.057491+0.000808
[265]	train-rmse:0.050459+0.000236	test-rmse:0.057489+0.000806
[266]	train-rmse:0.050446+0.000227	test-rmse:0.057487+0.000808
[267]	train-rmse:0.050439+0.000235	test-rmse:0.057486+0.000808
[268]	train-rmse:0.050432+0.000233	test-rmse:0.057486+0.000807
[269]	train-rmse:0.050418+0.000230	test-rmse:0.057483+0.000808
[270]	train-rmse:0.050393+0.000220	test-rmse:0.057477+0.000808
[271]	train-rmse:0.050376+0.000221	test-rmse:0.057475+0.000809
[272]	train-rmse:0.050359+0.000224	test-rmse:0.057472+0.000810
[273]	train-rmse:0.050348+0.000224	test-rmse:0.057470+0.000809
[274]	train-rmse:0.050336+0.000232	test-rmse:0.057467+0.000807
[275]	train-rmse:0.050322+0.000238	test-rmse:0.057462+0.000805
[276]	train-rmse:0.050315+0.000241	test-rmse:0.057460+0.000802
[277]	train-rmse:0.050293+0.000240	test-rmse:0.057454+0.000801
[278]	train-rmse:0.050288+0.000234	test-rmse:0.057453+0.000803
[279]	train-rmse:0.050278+0.000232	test-rmse:0.057445+0.000808
[280]	train-rmse:0.050271+0.000236	test-rmse:0.057442+0.000804
[281]	train-rmse:0.050256+0.000237	test-rmse:0.057439+0.000802
[282]	train-rmse:0.050252+0.000240	test-rmse:0.057439+0.000801
[283]	train-rmse:0.050243+0.000243	test-rmse:0.057437+0.000799
[284]	train-rmse:0.050238+0.000248	test-rmse:0.057436+0.000797
[285]	train-rmse:0.050234+0.000251	test-rmse:0.057434+0.000797
[286]	train-rmse:0.050217+0.000262	test-rmse:0.057429+0.000796
[287]	train-rmse:0.050205+0.000266	test-rmse:0.057426+0.000797
[288]	train-rmse:0.050202+0.000269	test-rmse:0.057425+0.000798
[289]	train-rmse:0.050200+0.000272	test-rmse:0.057424+0.000796
[290]	train-rmse:0.050191+0.000274	test-rmse:0.057423+0.000796
[291]	train-rmse:0.050183+0.000270	test-rmse:0.057421+0.000796
[292]	train-rmse:0.050168+0.000276	test-rmse:0.057414+0.000789
[293]	train-rmse:0.050160+0.000281	test-rmse:0.057412+0.000787
[294]	train-rmse:0.050150+0.000277	test-rmse:0.057405+0.000785
[295]	train-rmse:0.050142+0.000284	test-rmse:0.057403+0.000783
[296]	train-rmse:0.050137+0.000282	test-rmse:0.057403+0.000782
[297]	train-rmse:0.050116+0.000290	test-rmse:0.057394+0.000781
[298]	train-rmse:0.050107+0.000291	test-rmse:0.057391+0.000782
[299]	train-rmse:0.050092+0.000287	test-rmse:0.057387+0.000782
[300]	train-rmse:0.050073+0.000287	test-rmse:0.057381+0.000781
[301]	train-rmse:0.050064+0.000282	test-rmse:0.057379+0.000781
[302]	train-rmse:0.050053+0.000280	test-rmse:0.057375+0.000782
[303]	train-rmse:0.050049+0.000282	test-rmse:0.057377+0.000783
[304]	train-rmse:0.050043+0.000276	test-rmse:0.057376+0.000785
[305]	train-rmse:0.050040+0.000280	test-rmse:0.057375+0.000783
[306]	train-rmse:0.050034+0.000282	test-rmse:0.057373+0.000784
[307]	train-rmse:0.050027+0.000281	test-rmse:0.057371+0.000785
[308]	train-rmse:0.050023+0.000277	test-rmse:0.057370+0.000787
[309]	train-rmse:0.050018+0.000283	test-rmse:0.057369+0.000786
[310]	train-rmse:0.050011+0.000284	test-rmse:0.057369+0.000785
[311]	train-rmse:0.049990+0.000283	test-rmse:0.057364+0.000785
[312]	train-rmse:0.049988+0.000286	test-rmse:0.057363+0.000784
[313]	train-rmse:0.049982+0.000283	test-rmse:0.057361+0.000786
[314]	train-rmse:0.049970+0.000291	test-rmse:0.057360+0.000786
[315]	train-rmse:0.049961+0.000298	test-rmse:0.057359+0.000785
[316]	train-rmse:0.049961+0.000298	test-rmse:0.057359+0.000784
[317]	train-rmse:0.049952+0.000296	test-rmse:0.057358+0.000783

In [16]:
print(fit_xgb_cv$niter)
print(fit_xgb_cv$best_iteration)
print(fit_xgb_cv$best_score)
tail(fit_xgb_cv$evaluation_log, 3)

[1] 1000
[1] 999
NULL

  iter train_rmse_mean train_rmse_std test_rmse_mean test_rmse_std
1  998 0.04738894      0.0006402942   0.05676356     0.0007030246
2  999 0.04738169      0.0006440357   0.05676322     0.0007028895
3 1000 0.04738169      0.0006440368   0.05676324     0.0007028473

## Train final model

In [13]:
best_iter

[1] 1997

In [ ]:
### start timer
time_start = Sys.time()

fit_xgb = xgboost::xgb.train(
    params  = param,
    data    = dtrain,
    nrounds = best_iter,
    verbose = 1
)

### end timer and show elapsed time
time_end = Sys.time()
print(time_end - time_start)

## Feature Importance

In [ ]:
dat_imp = xgboost::xgb.importance(model = fit_xgb)

head(dat_imp, 20)